export const encounters = {
  VITALS: "ba05bfc0-8d80-11d8-abbb-0024217bb78e",
  AIRWAY_BREATHING: "e8322627-662a-4a88-aa69-925ca5a39161",
  SOCIAL_HISTORY: "ba063f0e-8d80-11d8-abbb-0024217bb78e",
  REFERRAL: "ba068946-8d80-11d8-abbb-0024217bb78e",
  BLOOD_CIRCULATION: "514ffff2-019e-4b3e-a85b-0df3dbd43228",
  CONSCIOUSNESS: "42bfe0d5-d05d-49d4-81d1-7e760d2ac003",
  PERSISTENT_PAIN: "5af651a4-de23-4a6e-84c4-60d7f98be243",
  AIRWAY_ASSESSMENT: "28fb4592-abc3-4b53-b13c-733595e2e504",
  BREATHING_ASSESSMENT: "08d4b4e5-dfa7-436b-9062-aee1b076c3ea",
  CIRCULATION_ASSESSMENT: "bb16ef97-6ef7-414f-880c-dfc67e1601df",
  EXPOSURE_ASSESSMENT: "00101c16-8441-43c6-a7f8-4bd20cf15cad",
  DISABILITY_ASSESSMENT: "0ef8f652-7852-49a5-a9dd-c1ca74fe098c",
  INITIAL_REGISTRATION: "4186b2dd-0254-4226-965a-e77fcaa70bcf",
  SCREENING_ENCOUNTER: "6878ece0-a61b-4e49-83b9-0468dd9eacfc",
  FINANCING: "ceec1aca-1bbb-427a-bc6d-ef8ae11f31b2",
  PRESENTING_COMPLAINTS: "ba069102-8d80-11d8-abbb-0024217bb78e",
  SAMPLE_HISTORY_PRESENTING_COMPLAINTS: "507e775e-1905-4e9a-bba9-dddbe1946db6",
  // TRIAGE_RESULT: "723ea21f-408e-4da5-a91f-56b0a8d0ce73",
  DISPOSITION: "ef689dc1-364f-4e18-b44f-36c5938c78da",
  TRIAGE_RESULT: "27e4890f-1677-4098-aa85-c65cfe32359c",
  CLINICAL_NOTES: "ba067294-8d80-11d8-abbb-0024217bb78e",
  PROCEDURES_DONE: "ba0656ec-8d80-11d8-abbb-0024217bb78e",
  NURSING_NOTES: "ba067294-8d80-11d8-abbb-0024217bb78e",
  OUTPATIENT_DIAGNOSIS: "ba05c128-8d80-11d8-abbb-0024217bb78e",
  LUNG_LEFT_UPPER_ZONE: "LEFT_UPPER_ZONE",
  LUNG_LEFT_MIDDLE_ZONE: "LEFT_MIDDLE_ZONE",
  LUNG_LEFT_LOWER_ZONE: "LEFT_LOWER_ZONE",
  LUNG_RIGHT_LOWER_ZONE: "RIGHT_LOWER_ZONE",
  LUNG_RIGHT_MIDDLE_ZONE: "RIGHT_MIDDLE_ZONE",
  LUNG_RIGHT_UPPER_ZONE: "RIGHT_UPPER_ZONE",
  LUNG_BACK_RIGHT_UPPER_ZONE: "LUNG_BACK_RIGHT_UPPER_ZONE",
  LUNG_BACK_LEFT_UPPER_ZONE: "LUNG_BACK_LEFT_UPPER_ZONE",
  LUNG_BACK_RIGHT_MIDDLE_ZONE: "LUNG_BACK_RIGHT_MIDDLE_ZONE",
  LUNG_BACK_LEFT_MIDDLE_ZONE: "LUNG_BACK_LEFT_MIDDLE_ZONE",
  LUNG_BACK_LEFT_LOWER_ZONE: "LUNG_BACK_LEFT_LOWER_ZONE",
  LUNG_BACK_RIGHT_LOWER_ZONE: "LUNG_BACK_RIGHT_LOWER_ZONE",
  ABDOMEN_RIGHT_HYPOCHONDRIUM: "ABDOMEN_RIGHT_HYPOCHONDRIUM",
  ABDOMEN_EPIGASTRIC_REGION: "ABDOMEN_EPIGASTRIC_REGION",
  ABDOMEN_LEFT_HYPOCHONDRIUM: "LEFT_HYPOCHONDRIUM",
  ABDOMEN_RIGHT_LUMBAR: "RIGHT_LUMBAR",
  ABDOMEN_LEFT_ILIAC_REGION: "LEFT_ILIAC_REGION",
  ABDOMEN_RIGHT_ILIAC_REGION: "RIGHT_ILIAC_REGION",
  ABDOMEN_UMBILICAL_REGION: "UMBILICAL_REGION",
  ABDOMEN_HYPOGASTRIUM: "HYPOGASTRIUM",
  ABDOMEN_LEFT_LUMBAR: "LEFT_LUMBAR",
  FULLBODY_LEFT_POPLITEAL: "FULLBODY_LEFT_POPLITEAL",
  FULLBODY_RIGHT_POPLITEAL: "FULLBODY_RIGHT_POPLITEAL",
  FULLBODY_RIGHT_GLUTEAL: "FULLBODY_RIGHT_GLUTEAL",
  FULLBODY_LEFT_GLUTEAL: "FULLBODY_LEFT_GLUTEAL",
  FULLBODY_LEFT_REAR_FEMORAL: "FULLBODY_LEFT_REAR_FEMORAL",
  FULLBODY_RIGHT_REAR_FEMORAL: "FULLBODY_RIGHT_REAR_FEMORAL",
  FULLBODY_REAR_CERVICAL: "FULLBODY_REAR_CERVICAL",
  FULLBODY_VERTEBRAL: "FULLBODY_VERTEBRAL",
  FULLBODY_SACRAL: "FULLBODY_SACRAL",
  FULLBODY_RIGHT_LUMBAR: "FULLBODY_RIGHT_LUMBAR",
  FULLBODY_LEFT_LUMBAR: "FULLBODY_LEFT_LUMBAR",
  FULLBODY_RIGHT_DORSAL_SCAPULAR: "FULLBODY_RIGHT_DORSAL_SCAPULAR",
  FULLBODY_LEFT_DORSAL_SCAPULAR: "FULLBODY_LEFT_DORSAL_SCAPULAR",
  FULLBODY_LEFT_OLECRANAL: "FULLBODY_LEFT_OLECRANAL",
  FULLBODY_RIGHT_OLECRANAL: "FULLBODY_RIGHT_OLECRANAL",
  FULLBODY_LEFT_REAR_BRACHIAL: "FULLBODY_LEFT_REAR_BRACHIAL",
  FULLBODY_RIGHT_REAR_BRACHIAL: "FULLBODY_RIGHT_REAR_BRACHIAL",
  FULLBODY_LEFT_REAR_ACROMIAL: "FULLBODY_LEFT_REAR_ACROMIAL",
  FULLBODY_RIGHT_REAR_ACROMIAL: "FULLBODY_RIGHT_REAR_ACROMIAL",
  FULLBODY_RIGHT_OTIC: "FULLBODY_RIGHT_OTIC",
  FULLBODY_LEFT_OTIC: "FULLBODY_LEFT_OTIC",
  FULLBODY_OCCIPUT: "FULLBODY_OCCIPUT",
  FULLBODY_LEFT_SURAL: "FULLBODY_LEFT_SURAL",
  FULLBODY_RIGHT_SURAL: "FULLBODY_RIGHT_SURAL",
  FULLBODY_LEFT_FIBULAR: "FULLBODY_LEFT_FIBULAR",
  FULLBODY_RIGHT_FIBULAR: "FULLBODY_RIGHT_FIBULAR",
  FULLBODY_LEFT_CALCANEAL: "FULLBODY_LEFT_CALCANEAL",
  FULLBODY_RIGHT_CALCANEAL: "FULLBODY_RIGHT_CALCANEAL",
  FULLBODY_LEFT_POSTERIOR_ANTEBRACHIAL: "FULLBODY_LEFT_POSTERIOR_ANTEBRACHIAL",
  FULLBODY_RIGHT_POSTERIOR_ANTEBRACHIAL:
    "FULLBODY_RIGHT_POSTERIOR_ANTEBRACHIAL",
  FULLBODY_INGUINAL: "FULLBODY_INGUINAL",
  FULLBODY_PUBIC: "FULLBODY_PUBIC",
  FULLBODY_PELVIC: "FULLBODY_PELVIC",
  FULLBODY_LEFT_FEMORAL: "FULLBODY_LEFT_FEMORAL",
  FULLBODY_LEFT_COXAL: "FULLBODY_LEFT_COXAL",
  FULLBODY_RIGHT_FEMORAL: "FULLBODY_RIGHT_FEMORAL",
  FULLBODY_RIGHT_COXAL: "FULLBODY_RIGHT_COXAL",
  FULLBODY_LEFT_PATELLAR: "FULLBODY_LEFT_PATELLAR",
  FULLBODY_RIGHT_PATELLAR: "FULLBODY_RIGHT_PATELLAR",
  FULLBODY_LEFT_CRURAL: "FULLBODY_LEFT_CRURAL",
  FULLBODY_LEFT_PERONEAL: "FULLBODY_LEFT_PERONEAL",
  FULLBODY_LEFT_TARSAL: "FULLBODY_LEFT_TARSAL",
  FULLBODY_RIGHT_CRURAL: "FULLBODY_RIGHT_CRURAL",
  FULLBODY_RIGHT_PERONEAL: "FULLBODY_RIGHT_PERONEAL",
  FULLBODY_RIGHT_PEDAL_DIGITAL: "FULLBODY_RIGHT_PEDAL_DIGITAL",
  FULLBODY_RIGHT_HALLUX: "FULLBODY_RIGHT_HALLUX",
  FULLBODY_RIGHT_PEDAL: "FULLBODY_RIGHT_PEDAL",
  FULLBODY_LEFT_HALLUX: "FULLBODY_LEFT_HALLUX",
  FULLBODY_LEFT_PEDAL_DIGITAL: "FULLBODY_LEFT_PEDAL_DIGITAL",
  FULLBODY_LEFT_PEDAL: "FULLBODY_LEFT_PEDAL",
  FULLBODY_LEFT_MANUS_DIGITAL: "FULLBODY_LEFT_MANUS_DIGITAL",
  FULLBODY_RIGHT_MANUS_DIGITAL: "FULLBODY_RIGHT_MANUS_DIGITAL",
  FULLBODY_RIGHT_MANUS_PALMAR: "FULLBODY_RIGHT_MANUS_PALMAR",
  FULLBODY_RIGHT_MANUS_POLLEX: "FULLBODY_RIGHT_MANUS_POLLEX",
  FULLBODY_RIGHT_CARPAL: "FULLBODY_RIGHT_CARPAL",
  FULLBODY_LEFT_CARPAL: "FULLBODY_LEFT_CARPAL",
  FULLBODY_LEFT_ANTEBRACHIAL: "FULLBODY_LEFT_ANTEBRACHIAL",
  FULLBODY_RIGHT_ANTEBRACHIAL: "FULLBODY_RIGHT_ANTEBRACHIAL",
  FULLBODY_LEFT_ANTECUBITAL: "FULLBODY_LEFT_ANTECUBITAL",
  FULLBODY_RIGHT_ANTECUBITAL: "FULLBODY_RIGHT_ANTECUBITAL",
  FULLBODY_RIGHT_BRACHIAL: "FULLBODY_RIGHT_BRACHIAL",
  FULLBODY_LEFT_BRACHIAL: "FULLBODY_LEFT_BRACHIAL",
  FULLBODY_ABDOMINAL: "FULLBODY_ABDOMINAL",
  FULLBODY_THORACIC_STERNAL: "FULLBODY_THORACIC_STERNAL",
  FULLBODY_LEFT_THORACIC_AXILLARY: "FULLBODY_LEFT_THORACIC_AXILLARY",
  FULLBODY_RIGHT_THORACIC_AXILLARY: "FULLBODY_RIGHT_THORACIC_AXILLARY",
  FULLBODY_RIGHT_THORACIC_MAMMARY: "FULLBODY_RIGHT_THORACIC_MAMMARY",
  FULLBODY_LEFT_THORACIC_MAMMARY: "FULLBODY_LEFT_THORACIC_MAMMARY",
  FULLBODY_RIGHT_ACROMIAL: "FULLBODY_RIGHT_ACROMIAL",
  FULLBODY_LEFT_ACROMIAL: "FULLBODY_LEFT_ACROMIAL",
  FULLBODY_CERVICAL: "FULLBODY_CERVICAL",
  FULLBODY_ORAL: "FULLBODY_ORAL",
  FULLBODY_MENTAL: "FULLBODY_MENTAL",
  FULLBODY_NASAL: "FULLBODY_NASAL",
  FULLBOD_LEFT_CEPHALIC_OBBITAL: "FULLBOD_LEFT_CEPHALIC_OBBITAL",
  FULLBOD_RIGHT_CEPHALIC_OBBITAL: "FULLBOD_RIGHT_CEPHALIC_OBBITAL",
  FULLBODY_CEPHALIC_FRONTAL: "FULLBODY_CERIGHT_PHALIC_FRONTAL",
  FULLBODY_RIGHT_CEPHALIC_BUCCAL: "FULLBODY_RIGHT_CEPHALIC_BUCCAL",
  FULLBODY_LEFT_CEPHALIC_BUCCAL: "FULLBODY_LEFT_CEPHALIC_BUCCAL",
  FULLBODY_RIGHT_CEPHALIC_ORBITAL: "FULLBODY_RIGHT_CEPHALIC_ORBITAL",
  FULLBODY_LEFT_CEPHALIC_ORBITAL: "FULLBODY_LEFT_CEPHALIC_ORBITAL",
  FULLBODY_LEFT_MANUS_POLLEX: "FULLBODY_LEFT_MANUS_POLLEX",
  FULLBODY_LEFT_MANUS_PALMAR: "FULLBODY_LEFT_MANUS_PALMAR",
  FULLBODY_RIGHT_TARSAL: "FULLBODY_RIGHT_TARSAL",
  HEAD_RIGHT_TEMPORAL: "Right_Temporal",
  HEAD_LEFT_TEMPORAL: "Left_Temporal",
  HEAD_CROWN: "Crown",
  HEAD_RIGHT_EYE: "Right_Eye",
  HEAD_LEFT_EYE: "Left_Eye",
  HEAD_NOSE: "Nose",
  HEAD_MOUTH: "Mouth",
  HEAD_NECK: "Neck",
  HEAD_FOREHEAD: "Forehead",
  HEAD_CHIN: "Chin",
  HEAD_RIGHT_CHEEK: "Right_Cheek",
  HEAD_LEFT_CHEEK: "Left_Cheek",
  HEAD_LEFT_EAR: "Left_Ear",
  HEAD_RIGHT_EAR: "Right_Ear",
  CHEST_ASSESSMENT: "8caec6aa-22c4-41f3-b81d-9454cac03b49",
  ABDOMEN_AND_PELVIS_ASSESSMENT: "36e596a7-dcd3-481c-83d7-adb8d63ac565",
  EXTREMITIES_ASSESSMENT: "5ddc1c09-8f2a-4e0a-ada7-fde717bd1f5b",
  NEUROLOGICAL_EXAMINATION_ASSESSMENT: "0f568068-9591-4455-a7f8-8ae9f86ca397",
  GENERAL_INFORMATION_ASSESSMENT: "dbda5bed-9326-4509-a4b2-760cb7862d5d",
  HEAD_AND_NECK_ASSESSMENT: "b43070c9-a4bf-4b05-84af-a8c45a37dfdd",
  MEDICAL_HISTORY: "ba05f13e-8d80-11d8-abbb-0024217bb78e",
  OBSTETRIC_HISTORY: "ba063da6-8d80-11d8-abbb-0024217bb78e",
  PRESCRIPTIONS: "88564b30-abaf-4744-8ea6-6e1c15465d9e",
  SOAPIER_PRESCRIPTION: "6e18d0c8-98b2-40fd-b116-25af7eef111d",
  SOAPIER_DISPENSING: "7def6325-4496-491a-a716-a9fca6e3c6df",
  ALLERGIES: "477f8110-ae4b-4caa-b608-c05b0f967b9e",
  DIAGNOSIS: "ba05fbfc-8d80-11d8-abbb-0024217bb78e",
  SURGICAL_HISTORY: "ba063e50-8d80-11d8-abbb-0024217bb78e", //Encounter exists for for ante-natal clinic but not for adults
  PATIENT_ADMISSIONS: "ba0651ec-8d80-11d8-abbb-0024217bb78e",
  SUMMARY_ASSESSMENT: "e5fec87c-9bea-42bb-a276-0469addccf99",

  // CPR:"8576645e-1661-47fc-90b4-12420148da8b",

  //TODO: replace this UUID with a bedside test
  CPR: "31582078-729a-45ca-935c-43bd7d4b382c",
  //TODO: replace this UUID with a bedside test
  BED_SIDE_TEST: "7d4400bf-534b-4c06-8b20-f6a424beb64c",
  BEDSIDE_INVESTIGATION_PLAN: "7168c660-552a-4855-b07e-95958d71948d",
  LAB_ORDERS_PLAN: "b1183b2e-ffc5-4ec5-b035-7f8a0189e2c6",
  LAB: "ba05c4c0-8d80-11d8-abbb-0024217bb78e",
  DISCHARGE_PATIENT: "ba06820c-8d80-11d8-abbb-0024217bb78e",
  TREATMENT: "ba05ed9c-8d80-11d8-abbb-0024217bb78e",
  NON_PHARMACOLOGICAL: "4b1f68fe-ea1b-4bde-bf97-e5f7a721c895",
  PATIENT_CARE_AREA: "d0d12af5-7f67-41fe-a856-db3b54ca6c0d",
  DISPENSING: "ba0612c2-8d80-11d8-abbb-0024217bb78e",
  FAMILY_MEDICAL_HISTORY: "ba06b178-8d80-11d8-abbb-0024217bb78e",
  REVIEW_OF_SYSTEMS: "54e32e5d-51c5-4f16-8cff-9fc7da3c68ca",
  NURSING_CARE_NOTES: "c7d8b240-04f0-48c1-8d83-10d95f571b92",
  TEMPLATE_NOTES: "ba067294-8d80-11d8-abbb-0024217bb78e",
  CONTINUATION_SHEET: "dd12d7ad-f177-463a-9013-c135440c6cf9",
  PRIMARY_DISABILITY_ASSESSMENT: "d3608295-ea61-4864-b0c7-eb3bc062a0e2",
  MEDICAL_IN_PATIENT: "1aeb209d-8f1f-4367-8d9c-476134235545",
  SURGICAL_NOTES_TEMPLATE_FORM: "6c44a2d9-953d-41dd-9b99-03b4214f85ba",
  DISPOSED_PRESCRIPTIONS: "a9ebe09e-0296-40d1-a9fa-3efcce85ea9e ",
  // GYNEACOLOGY_WARD: "59514a38-a019-4833-b180-480d1bbf2dfe",
  GYNEACOLOGY_WARD: "7819932d-eea1-43d2-a543-35cb93f2da49",
  AWAITING_SPECIALTY: "4a10d674-9072-4385-b2e9-583d0524abe1",
  SAMPLE_HISTORY_MEDICATION: "d4a76565-efac-46b3-9ac9-db6e1c76aec6",
};

export const AETC_VISIT_TYPE = "9f825d6a-50e6-44e1-a1a4-5cd343963ecc";
export const YES = "Yes";
export const NO = "No";

export const concepts = {
  COMPLAINTS: "Complaints",
  EMERGENCY: "Emergency",
  URGENT: "Urgent",
  NOT_INDICATED: "Not Indicated",
  DONE: "Done",
  NOT_DONE: "Not Done",
  BP_NOT_RECORDABLE: "Bp Not Recordable",
  PATIENT_UNCOOPERATIVE: "Patient Uncooperative",
  MACHINE_NOT_AVAILABLE: "Machine Not Available",
  BATTERIES_NOT_AVAILABLE: "Batteries Not Available",
  INAPPROPRIATELY_SIZED_CUFF: "Inappropriately Sized Cuff",
  NO_POWER_SUPPLY: "No Power Supply",
  IMAGE_PART_NAME: "Image Part Name",
  SELECTED_SECTION: "Selected Section",
  DOSE_IN_MILLIMETERS: "Dose In Millimeters",
  MEDICATION_LAST_TAKEN: "Medication Last Taken",
  MEDICATION_LAST_PRESCRIBED: "Medication Last Prescribed",
  DISCHARGE_HOME: "Discharge Home",
  AWAITING_SPECIALITY_REVIEW: "Awaiting Speciality Review",
  ADMISSION: "Admission",
  THEATRE: "Theatre",
  OTHER_INTERVENTION_SUITE: "Other Intervention Suite",
  SHORT_STAY: "Short stay",
  // TRANSFER_TO_ANOTHER_FACILITY: "Transfer To Another Facility",
  TRANSFER_OUT: "Transfer Out",
  DEATH: "Death",
  ABSCONDED: "Absconded",
  REFUSED_HOSPITAL_TREATMENT: "Refused Hospital Treatment",
  DISCHARGE_PLAN: "Discharge Plan",
  FOLLOWUP_PLAN: "Followup Plan",
  HOME_CARE_INSTRUCTIONS: "Home Care Instructions",
  FOLLOWUP_DETAILS: "Followup Details",
  HEALTH_CENTER: "Health Center",
  SPECIALIST_CLINIC: "Specialist clinic",
  DISTRICT_HOSPITAL: "District Hospital",
  DISCHARGE_NOTES: "Discharge Notes",
  REASON_FOR_REQUEST: "Reason for request",
  SPECIALITY_DEPARTMENT: "Speciality Department",
  MEDICINE: "Medicine",
  GENERAL_SURGERY: "General Surgery",
  ORTHOPEDICS: "Orthopedics",
  NEUROSURGERY: "Neurosurgery",
  EAR_NOSE_AND_THROAT_ENT: "Ear Nose And Throat Ent",
  DENTAL_AND_MAXILLOFACIAL_SURGERY: "Dental And Maxillofacial Surgery",
  OPHTHALMOLOGY: "Ophthalmology",
  PSYCHIATRY: "Psychiatry",
  GYNAECOLOGY_AND_OBSTETRICS: "Gynaecology And Obstetrics",
  CRITICAL_CARE: "Critical Care",
  ONCOLOGY: "Oncology",
  WARD: "Ward",
  TWO_A_ONCOLOGY_WARD_GENERAL_WARD_HIGH_DEPENDENCY_UNIT:
    "2A Oncology Ward General Ward High Dependency Unit",
  TWO_B_RENAL_AND_DERMATOLOGY_WARD: "2B Renal And Dermatology Ward",
  SIX_A_FEMALE_ORTHOPAEDIC_WARD: "6A Female Orthopaedic Ward",
  FOUR_A_FEMALE_MEDICAL_WARD_GENERAL_WARD_HIGH_DEPENDENCY_UNIT:
    "4A Female Medical Ward General Ward High Dependency Unit",
  GYNECOLOGY_WARD_GENERAL_WARD_HIGH_DEPENDENCY_UNIT:
    "Gynecology Ward General Ward High Dependency Unit",
  LABOUR_WARD_GENERAL_WARD_HIGH_DEPENDENCY_UNIT:
    "Labour Ward General Ward High Dependency Unit",
  THREE_B_FEMALE_MEDICAL_WARD_GENERAL_WARD_HIGH_DEPENDENCY_UNIT:
    "3B Female Medical Ward General Ward High Dependency Unit",
  THREE_A_TB_WARD: "3A Tb Ward",
  THREE_A_HDRU_HIGH_DEPENDENCY_RESPIRATORY_UNIT:
    "3A Hdru High Dependency Respiratory Unit",
  FIVE_A_MALE_SURGICAL_WARD_GENERAL_WARD_HIGH_DEPENDENCY_UNIT:
    "5A Male Surgical Ward General Ward High Dependency Unit",
  FIVE_B_FEMALE_SURGICAL_WARD_GENERAL_WARD_HIGH_DEPENDENCY_UNIT:
    "5B Female Surgical Ward General Ward High Dependency Unit",
  FIVE_B_ORTHOPAEDIC_WARD: "5B Orthopaedic Ward",
  FIVE_B_NEUROSURGICAL_WARD_GENERAL_WARD_HIGH_DEPENDENCY_UNIT:
    "5B Neurosurgical Ward General Ward High Dependency Unit",
  ONE_A_LABOUR_WARD: "1A Labour ward",
  MAIN_LABOUR_WARD: "Main Labour ward",
  ANTENATAL_WARD: "Antenatal ward",
  POST_NATAL_WARD: "Post natal ward",
  GYNAECOLOGY_WARD_MAIN: "Gynaecology ward- Main",
  THREE_B_MALE_MEDICAL: "3B Male medical",
  THREE_C_COMBINED_MALE_AND_FEMALE_MEDICAL:
    "3C Combined male and female medical",
  SIX_A_ORTHOPAEDIC_MALE: "6A Orthopaedic male",
  THREE_B_HDU: "3B High Dependency Unit",
  MSF_WARD_GYNAECOLOGY: "MSF ward - Gynaecology",
  FOUR_A_FEMALE_WARD: "4A Female ward",
  FOUR_A_HDU: "4A HDU",

  INTENSIVE_CARE_UNIT_ICU: "Intensive Care Unit Icu",
  ENT: "Ent",
  BED_NUMBER: "Bed Number",
  REASON_FOR_ADMISSION: "Reason for admission",
  EXPECTED_DURATION: "Expected Duration",
  VITAL_SIGNS: "Vital Signs",
  SOAP_NOTES: "Soap Notes",
  FACILITY_NAME: "Facility Name",
  REASON_FOR_TRANSFER: "Reason For Transfer",
  CAUSE_OF_DEATH: "Cause of death",
  FAMILY_INFORMED: "Family Informed",
  RELATIONSHIP_TO_DECEASED: "Relationship To Deceased",
  RELATIONSHIP_SPOUSE: "Relationship Spouse",
  RELATIONSHIP_PARENT: "Relationship Parent",
  RELATIONSHIP_SIBLING: "Relationship Sibling",
  RELATIONSHIP_UNCLE: "Relationship Uncle",
  RELATIONSHIP_COUSIN: "Relationship Cousin",
  RELATIONSHIP_OTHER: "Relationship Other",
  MORTUARY: "Mortuary",
  QECH: "Qech",
  COM: "Com",
  MTHUNZI: "Mthunzi",
  LAST_OFFICE_CONDUCTED: "Last Office Conducted",
  NAME_OF_HEALTH_WORKER_WHO_CONDUCTED_LAST_OFFICE:
    "Name Of Health Worker Who Conducted Last Office",
  DATE_OF_LAST_OFFICE: "Date Of Last Office",
  LAST_SEEN_LOCATION: "Last Seen Location",
  DATE_OF_ABSCONDING: "Date Of Absconding",
  TIME_OF_ABSCONDING: "Time Of Absconding",
  REASON_FOR_REFUSAL: "Reason For Refusal",
  PLANS_TO_RETURN_FOR_TREATMENT: "Plans To Return For Treatment",
  DATE_OF_REFUSAL: "Date Of Refusal",
  WITNESS_NAME: "Witness Name",
  PROCEDURES: "Procedures",
  MINOR_SURGERY: "Minor Surgery",
  SUTURING: "Suturing",
  JOINT_REDUCTION: "Joint Reduction",
  FRACTURE_REDUCTION: "Fracture Reduction",
  INTERCOSTAL_DRAIN_INSERTION: "Intercostal Drain Insertion",
  PLEUROCENTESIS: "Pleurocentesis",
  PERICARDIOCENTESISI: "Pericardiocentesisi",
  PARACENTESISI: "Paracentesisi",
  LUMBER_PUNCTURE: "Lumber Puncture",
  INTRAVENOUS_CANNULATION: "Intravenous Cannulation",
  CENTRAL_LINE_INSERTION: "Central Line Insertion",
  CATHETERIZATION_URETHRAL: "Catheterization Urethral",
  CATHETERIZATION_SUPRAPUBIC: "Catheterization Suprapubic",
  OROPHARYNGEAL_AIRWAY_INSERTION: "Oropharyngeal Airway Insertion",
  NASOPHARYNGEAL_AIRWAY_INSERTION: "Nasopharyngeal Airway Insertion",
  LARYNGEAL_MASK_AIRWAY_INSERTION: "Laryngeal Mask Airway Insertion",
  ENDOTRACHEAL_TUBE_INSERTION: "Endotracheal Tube Insertion",
  NASOGASTRIC_TUBE_INSERTION: "Nasogastric Tube Insertion",
  MANUAL_VENTILATION: "Manual Ventilation",
  CONTINUOUS_POSITIVE_AIRWAY_PRESSURE: "Continuous Positive Airway Pressure",
  SUPPORTIVE_CARE: "Supportive Care",
  WOUND_DRESSING: "Wound Dressing",
  PATIENT_EDUCATION: "Patient Education",
  COUNSELLING: "Counselling",
  FEEDING: "Feeding",
  OXYGENATION: "Oxygenation",
  TAPID_SPONGING: "Tapid Sponging",
  TEPID_SPONGING: "Tepid Sponging",
  ELECTROCARDIOGRAPHY_MONITORING: "Electrocardiography Monitoring",
  TURNING_PATIENTS: "Turning Patients",
  ORAL_CARE: "Oral Care",
  TRAUMA: "Trauma",
  CARE_AREA: "Patient care area",
  GYNO: "Gyno",
  SURGICAL: "Surgical",
  MEDICAL_BENCH: "Medical Bench",
  SHORT_STAY_AREA: "Short Stay Area",
  ISOLATION: "Isolation",
  TEMPERATURE: "Temperature",
  RESPIRATORY_RATE: "Respiratory Rate",
  SATURATION_RATE: "Saturation Rate",
  BLOOD_OXYGEN_SATURATION: "Blood oxygen saturation",
  HEART_RATE: "Heart Rate",
  BLOOD_PRESSURE_SYSTOLIC: "Blood Pressure Systolic",
  BLOOD_PRESSURE_DIASTOLIC: "Blood Pressure Diastolic",
  SYSTOLIC_BLOOD_PRESSURE: "Systolic blood pressure",
  DIASTOLIC_BLOOD_PRESSURE: "Diastolic blood pressure",
  MOTOR_RESPONSE: "Motor Response",
  EYE_OPENING_RESPONSE: "Eye Opening Response",
  VERBAL_RESPONSE: "Verbal Response",
  GLUCOSE: "Blood glucose",
  MEDICAL_RECORD_OBSERVATIONS: "Medical record observations",
  AVPU: "Avpu",
  PULSE_OXIMETRY: "Pulse Oximetry",
  PULSE_RATE: "Pulse Rate",
  URINE_DIPSTICK_KETONES: "Urine Dipstick Ketones",
  PEAK_EXPIRATORY_FLOW_RATE: "Peak Expiratory Flow Rate",
  CONDITION: "Condition",
  DIFFERENTIAL_DIAGNOSIS: "Attempted/ Differential Diagnosis",
  FINAL_DIAGNOSIS: "Final Diagnosis",
  IS_AIRWAY_COMPROMISED: "Is Airway Compromised",
  IS_BREATHING_ABNORMAL: "Is Breathing Abnormal",
  OXYGEN_STATS_89: "Oxygen Stats 89",
  RESPIRATORY_RATE_8_31: "Respiratory Rate 8 31",
  SEVERE_RESPIRATORY: "Severe Respiratory",
  INABILITY_TO_SPEAK: "Inability To Speak",
  REDUCED_LEVEL_CONSCIOUSNESS: "Reduced Level Consciousness",
  OXYGEN_STATS_90_92: "Oxygen Stats 90 92",
  RESPIRATORY_RATE_9_21_30: "Respiratory Rate 9 21 30",
  YES: "Yes",
  NO: "No",
  AIRWAY_OPENING_INTERVENTIONS: "Airway Opening Interventions",
  FOREIGN_BODY_REMOVAL: "Foreign Body Removal",
  SUCTIONING: "Suctioning",
  POSITIONING: "Positioning",
  C_SPINE_STABILIZATION: "C Spine Stabilization",
  INSERTION_OF_GUEDEL: "Insertion Of Guedel",
  OTHER_AIRWAY_INTERVENTION: "Other Airway Intervention",
  IS_CIRCULATION_ABNORMAL: "Is Circulation Abnormal",
  HEART_RATE_50_120: "Heart Rate 50 120",
  REDUCED_URINARY_OUTPUT: "Reduced Urinary Output",
  CAPILLARY_REFILL: "Capillary Refill",
  WEAK_THREADY: "Weak Thready",
  HEMORRHAGE: "Hemorrhage",
  DEHYDRATION_SKIN: "Dehydration Skin",
  HEART_RATE_50: "Heart Rate 50",
  CIRCULATION_INTERVENTIONS: "Circulation Interventions",
  DISABILITY_INTERVENTIONS: "Disability Interventions",
  EXPOSURE_INTERVENTIONS: "Exposure Interventions",
  DOES_PATIENT_LOW_LEVEL_CONSCIOUSNESS: "Does Patient Low Level Consciousness",
  BLOOD_GLUCOSE: "Blood glucose",
  GCS: "Gcs",
  MARITAL_STATUS: "Marital Status",
  OCCUPATION: "Occupation",
  RELIGION: "Religion",
  HIGHEST_EDUCATION: "Highest Education",
  METHOD_OF_TRANSPORTATION: "Method Of Transportation",
  ACTIVE_SEIZURES: "Active Seizures",
  FOCAL_NEUROLOGICAL: "Focal Neurological",
  WEAKNESS: "Weakness",
  SEVERE_PAIN: "Severe Pain",
  MODERATE_PAIN: "Moderate Pain",
  AIRWAY_PATENT: "Airway Patent",
  PATIENT_INJURED: "Patient Injured",
  NECK_COLLAR_APPLIED: "Neck Collar Applied",
  HEAD_BLOCKS_APPLIED: "Head Blocks Applied",
  AIRWAY_OPENING_INTERVENTION: "Airway Opening Intervention",
  NASOPHARYNGEAL_AIRWAY: "Nasopharyngeal Airway",
  OROPHARYNGEAL_AIRWAY: "Oropharyngeal Airway",
  AIRWAY_REASON: "Airway Reason",
  IS_PATIENT_BREATHING: "Is Patient Breathing",
  OXYGEN_SATURATION: "Oxygen Saturation",
  PATIENT_NEED_OXYGEN: "Patient Need Oxygen",
  IS_TRACHEA_CENTRAL: "Is Trachea Central",
  OXYGEN_GIVEN: "Oxygen Given",
  OXYGEN_SOURCE: "Oxygen Source",
  DEVICE_USED: "Device Used",
  CHEST_WALL_ABNORMALITY: "Chest Wall Abnormality",
  CHEST_EXPANSION: "Chest Expansion",
  PERCUSSION: "Percussion",
  SIDE_DEVIATED: "Side Deviated",
  START_TIME: "Start Time",
  END_TIME: "End Time",
  DEVICE_USED_FOR_INTERVENTION: "Device Used For Intervention",
  ADDITIONAL_NOTES: "Additional Notes",
  NONE: "None",
  DESCRIPTION: "Description",
  BREATHING_INTERVENTIONS: "Breathing Interventions",
  BAG_AND_MASK: "Bag And Mask",
  INTERCOSTAL_DRAINAGE: "Intercostal Drainage",
  SUBJECTIVE_DATA: "Subjective Data",
  OBJECTIVE_DATA: "Objective Data",
  BEDSIDE_INVESTIGATIONS: "Bedside Investigations",
  ASSESSMENT_COMMENTS: "Assessment Comments",
  TREATMENT_PLAN: "Treatment Plan",
  INTERVENTION_NOTES: "Intervention Notes",
  IS_PATIENT_ACTIVELY_BLEEDING: "Is Patient Actively Bleeding",
  IS_THE_PATIENT_HAVE_PULSE: "Is The Patient Have Pulse",
  CAPILLARY_REFILL_TIME: "Capillary Refill Time",
  MUCOUS_MEMBRANES: "Mucous Membranes",
  PULSE_RATE_WEAK: "Pulse Rate Weak",
  ASSESS_PERIPHERIES: "Assess Peripheries",
  BLOOD_PRESSURE_MEASURED: "Blood Pressure Measured",
  PATIENT_INTRAVENOUS: "Patient Intravenous",
  IS_PATIENT_TRAUMATIZED: "Is Patient Traumatized",
  SIZE_OF_CATHETER: "Size Of Catheter",
  IS_PELVIS_STABLE: "Is Pelvis Stable",
  IS_FEMUR_TIBIA_NORMAL: "Is Femur Tibia Normal",
  INTAKE_FLUIDS: "Intake Fluids",
  IS_ABDONORMINAL_DISTENTION: "Is Abdonorminal Distention",
  IS_THERE_OTHER_OBDONORMALITIES: "Is There Other Obdonormalities",
  IS_THERE_ANY_OTHER_ABNOMALITIES: "Is There Any Other Abnomalities",
  ACTION_DONE: "Action Done",
  REASON_NOT_RECORDED: "Reason Not Recorded",
  PUPIL_SIZE_AND_REACTION_TO_LIGHT: "Pupil Size And Reaction To Light",
  POSTURE: "Posture",
  FOCAL_NEUROLOGY: "Focal Neurology",
  SEIZURES: "Seizures",
  VISIT_NUMBER: "Aetc Visit Number",
  IS_PATIENT_REFERRED: "Is Patient Referred",
  IS_SITUATION_URGENT: "Is Situation Urgent",
  PATIENT_REFERRED_TO: "Patient Referred To",
  NATIONAL_ID_IDENTIFIER_TYPE: "National Id Identifier Type",
  PARENT: "8d91a210-c2cc-11de-8d13-0010c6dffd0f",
  UNCLE_AUNTIE: "8d91a3dc-c2cc-11de-8d13-0010c6dffd0f",
  AUNTIE: "68e31ef5-113f-46a9-b34c-98302611e5fd",
  GUARDIAN: "ba453344-8d80-11d8-abbb-0024217bb78e",
  SPOUSE: "c397168a-f8bd-4ad1-b865-e608c1f3487e",
  SIBLING: "8d91a01c-c2cc-11de-8d13-0010c6dffd0f",
  REFERRED_FROM: "Referred From",
  INSURANCE_PROVIDER: "Insurance Provider",
  INSURANCE_NUMBER: "Insurance Number",
  INSURANCE_SCHEME: "Insurance Scheme",
  INSURANCE_STATUS: "Insurance Status",
  PAYMENT_OPTIONS: "Payment Options",
  TRIAGE_RESULT: "Triage Result",
  ELECTIVE: "Elective",
  CURRENT_COMPLAINTS_OR_SYMPTOMS: "Current Complaints Or Symptoms",
  DURATION_OF_SYMPTOMS_HOURS: "Duration Of Symptoms Hours",
  DURATION_OF_SYMPTOMS_DAYS: "Duration Of Symptoms Days",
  DURATION_OF_SYMPTOMS_WEEKS: "Duration Of Symptoms Weeks",
  DURATION_OF_SYMPTOMS_MONTHS: "Duration Of Symptoms Months",
  DURATION_OF_SYMPTOMS_YEARS: "Duration Of Symptoms Years",
  INVESTIGATIONS: "Laboratory Investigations",
  PRESENTING_HISTORY: "Presenting History",
  PUPIL_SIZE: "Pupil Size",
  PALLOR: "Pallor",
  JAUNDICE: "Jaundice",
  RACCOON_EYES: "Raccoon Eyes",
  HYPHEMA: "Hyphema",
  EYELID_INJURY: "Eyelid Injury",
  FUNDOSCOPY: "Fundoscopy",
  FUNDOSCOPY_FINDING: "Fundoscopy Finding",
  ORAL_THRUSH: "Oral Thrush",
  KAPOSI_SARCOMA_LESIONS: "Kaposi Sarcoma Lesions",
  TONGUE_LACERATION: "Tongue Laceration",
  LOOSE_TEETH: "Loose Teeth",
  BLEEDING_FROM_EAR: "Bleeding From Ear",
  OTORRHOEA: "Otorrhoea",
  LACERATION: "Laceration",
  LACERATION_LENGTH: "Laceration Length",
  LACERATION_DEPTH: "Laceration Depth",
  LACERATION_OTHER: "Laceration Other",
  OTOSCOPY: "Otoscopy",
  OTOSCOPY_FINDINGS: "Otoscopy Findings",
  BLEEDING_FROM_INSIDE: "Bleeding From Inside",
  RHINORRHOEA: "Rhinorrhoea",
  LEFT_TEMPORAL: "Left Temporal",
  RIGHT_TEMPORAL: "Right Temporal",
  OCCIPUT: "Occiput",
  CROWN: "Crown",
  ABNORMALITIES: "Abnormalities",
  BRUISE: "Bruise",
  HAEMATOMA: "Haematoma",
  FRACTURE: "Fracture",
  OTHER: "Other",
  TRACHEA: "Trachea",
  TRACHEA_DEVIATED: "Trachea Deviated",
  JUGULAR_VENOUS_PRESSURE: "Jugular Venous Pressure",
  RAISED: "Raised",
  RAISED_HEIGHT: "Raised Height",
  ENLARGED_THYROID: "Enlarged Thyroid",
  LYMPH_NODES: "Lymph Nodes",
  LOCATION: "Location",
  SIZE: "Size",
  MOBILITY: "Mobility",
  TENDERNESS: "Tenderness",
  PECTUS_EXCAVATUM: "Pectus Excavatum",
  PECTUS_CARINATUM: "Pectus Carinatum",
  BARREL_CHEST: "Barrel Chest",
  LOCALISED_CHEST_WALL_ABNORMALITY: "Localised Chest Wall Abnormality",
  NORMAL: "Normal",
  REDUCED: "Reduced",
  INCREASED: "Increased",
  TACTILE_FREMITUS: "Tactile Fremitus",
  APEX_BEAT: "Apex Beat",
  DISPLACED: "Displaced",
  NOT_DISPLACED: "Not Displaced",
  TRILL: "Trill",
  HEAVES: "Heaves",
  HEAVES_DESCRIPTION: "Heaves Description",
  ABNORMAL: "Abnormal",
  HYPERRESONANT: "Hyperresonant",
  DULL: "Dull",
  STONY_DULL: "Stony Dull",
  BREATHING_SOUNDS: "Breathing Sounds",
  ABSENT: "Absent",
  ADDED: "Added",
  CRACKLES: "Crackles",
  WHEEZES: "Wheezes",
  BRONCHIAL: "Bronchial",
  VOCAL_FREMITUS: "Vocal Fremitus",
  HEART_SOUNDS: "Heart Sounds",
  LOUD_P2: "Loud P2",
  SPLITTING_P2: "Splitting P2",
  GALLOP_RHYTHM: "Gallop Rhythm",
  MURMUR: "Murmur",
  TYPE_OF_MURMUR: "Type Of Murmur",
  ABDOMINAL_DISTENTION: "Abdominal Distention",
  ABNORMALITIES_PRESENT: "Abnormalities Present",
  SUPERFICIAL: "Superficial",
  PARTIAL: "Partial",
  THICKNESS: "Thickness",
  FULL_THICKNESS: "Full Thickness",
  STAB_PUNCTURE: "Stab Puncture",
  BURNS: "Burns",
  SCAR: "Scar",
  FLAT: "Flat",
  DISTENDED: "Distended",
  ASYMMETRICAL: "Asymmetrical",
  SURGICAL_SCAR: "Surgical Scar",
  STRETCH_MARKS: "Stretch Marks",
  HEPATOMEGALY: "Hepatomegaly",
  HEPATOMEGALY_DESCRIPTION: "Hepatomegaly Description",
  SPLENOMEGALY: "Splenomegaly",
  SPLENOMEGALY_DESCRIPTION: "Splenomegaly Description",
  KIDNEYS_BALLOTABLE: "Kidneys Ballotable",
  FULL_BLADDER: "Full Bladder",
  OTHER_MASSES: "Other Masses",
  OTHER_MASSES_DESCRIPTION: "Other Masses Description",
  SHIFTING_DULLNESS: "Shifting Dullness",
  FLUID_THRILL: "Fluid Thrill",
  BRUIT: "Bruit",
  BOWEL_SOUNDS: "Bowel Sounds",
  HYPERACTIVE: "Hyperactive",
  REDUCED_BOWEL_SOUNDS: "Reduced Bowel Sounds",
  GENERAL: "General",
  EMPTY_RECTUM: "Empty Rectum",
  MALAENA: "Malaena",
  FRESH_BLOOD: "Fresh Blood",
  PROSTATE: "Prostate",
  ENLARGED: "Enlarged",
  HIGH_RIDING: "High Riding",
  MASS: "Mass",
  SPHINCTER_TONE: "Sphincter Tone",
  ULCERATIONS: "Ulcerations",
  BITE_MARKS: "Bite Marks",
  OEDEMA: "Oedema",
  CIRCUMCISION_STATUS: "Circumcision Status",
  UNUSUAL_SIZE_APPEARANCE_OF_CLITORIS: "Unusual Size Appearance Of Clitoris",
  URETHRAL_MEATUS: "Urethral Meatus",
  EDEMA: "Edema",
  LESIONS: "Lesions",
  BLEEDING: "Bleeding",
  VAGINA: "Vagina",
  SCROTUM: "Scrotum",
  ERYTHEMA: "Erythema",
  ECCHYMOSES: "Ecchymoses",
  ABRASIONS: "Abrasions",
  SWELLING: "Swelling",
  GENERAL_INSPECTION: "General Inspection",
  PERIHYMEN: "Perihymen",
  HEMATOMAS: "Hematomas",
  DISCOLORATIONS: "Discolorations",
  INFLAMMATION: "Inflammation",
  ODEMA: "Odema",
  DISCHARGE: "Discharge",
  DIGITAL_VAGINAL_EXAMINATION: "Digital Vaginal Examination",
  FOREIGN_BODIES: "Foreign Bodies",
  PALPABLE_ABNORMALITIES: "Palpable Abnormalities",
  PELVIC_EXAMINATION: "Pelvic Examination",
  OEDEMA_DETAILS: "Oedema Details",
  FEET_ONLY: "Feet Only",
  UP_TO_KNEE: "Up To Knee",
  UP_TO_THIGH: "Up To Thigh",
  WHOLE_BODY: "Whole Body",
  COLD_CLAMMY: "Cold Clammy",
  ABNORMALITIES_UPPER_LIMB: "Abnormalities Upper Limb",
  ABNORMALITIES_LOWER_LIMB: "Abnormalities Lower Limb",
  DEFORMITY: "Deformity",
  CREPITUS: "Crepitus",
  SCARS: "Scars",
  RASH: "Rash",
  FRACTURE_DESCRIPTION: "Fracture Description",
  DEFORMITY_DESCRIPTION: "Deformity Description",
  MASS_DESCRIPTION: "Mass Description",
  BURNS_DESCRIPTION: "Burns Description",
  SPECIFY: "Specify",
  PETECHIAE: "Petechiae",
  URTICARIA: "Urticaria",
  BITE: "Bite",
  STING: "Sting",
  MACULE: "Macule",
  PAPULE: "Papule",
  VESICLE: "Vesicle",
  PUSTULE: "Pustule",
  BULLAE: "Bullae",
  SCALE: "Scale",
  SKIN_RASH: "Skin Rash",
  INTEGUMENTARY: "Integumentary",
  CHANGES_IN_MOLES: "Changes in Moles",
  MOOD_CHANGES: "Mood Changes",
  INCREASE_URINARY_FREQUENCY: "Increased Urinary Frequency",
  REDUCED_URINARY_FREQUENCY: "Reduced Urinary Frequency",
  STIFFNESS: "Stiffness",
  VISION_CHANGES: "Vision changes",
  NASAL_STUFFINESS: "Nasal Stuffness",
  INJURY: "Injury",
  WOUND: "Wound",
  TESTICLES: "Testicles",
  TESTICLES_NOTES: "Testicles Notes",
  DIGITAL_VAGINAL_EXAMINATION_NOTES: "Digital Vaginal Examination Notes",
  UNUSUAL_APPEARANCE_NOTES: "Unusual Appearance Notes",
  PERIHYMEN_NOTES: "Perihymen Notes",
  VAGINA_NOTES: "Vagina Notes",
  URETHRAL_NOTES: "Urethral Notes",
  SCROTUM_NOTES: "Scrotum Notes",
  THREATENED: "Threatened",
  SECRETION: "Secretion",
  TONGUE_SWELLING: "Tongue Swelling",
  NECK_SWELLING: "Neck Swelling",
  NECK_HAEMATOMA: "Neck Haematoma",
  TONGUE_FALLING_BACK: "Tongue Falling Back",
  SUCTIONING_DONE: "Suctioning Done",
  JAW_THRUST_MANOEUVER: "Jaw Thrust Manoeuver",
  HEAD_TILT_CHIN_LIFT: "Head Tilt Chin Lift",
  OROPHARYNGEAL: "Oropharyngeal",
  CONCENTRATOR: "Concentrator",
  CYLINDER: "Cylinder",
  PIPED_OXYGEN: "Piped Oxygen",
  NASAL_PRONGS: "Nasal Prongs",
  SIMPLE_FACE_MASK: "Simple Face Mask",
  VENTURI_FACE_MASK: "Venturi Face Mask",
  NEBULISING_CHAMBER: "Nebulising Chamber",
  NON_REBREATHER: "Non Rebreather",
  NON_INVASIVE_VENTILATION_MASK: "Non Invasive Ventilation Mask",
  LARYNGEAL: "Laryngeal",
  ENDOTRACHEAL: "Endotracheal",
  FLAIL_CHEST: "Flail Chest",
  SURGICAL_EMPHYSEMA: "Surgical Emphysema",
  LARYNGEAL_MASK_AIRWAY_AND_BAG: "Laryngeal Mask Airway And Bag",
  LEFT: "Left",
  RIGHT: "Right",
  RIB_DEFORMITY: "Rib Deformity",
  FAIL_CHEST: "Fail Chest",
  IMAGE_ENCOUNTER: "Image Encounter",
  IMAGE_SECTION: "Image Section",
  PALE: "Pale",
  CYANOSIS: "Cyanosis",
  WEAK: "Weak",
  STRONG_REGULAR: "Strong Regular",
  IRREGULAR: "Irregular",
  REGULAR_RHYTHM: "Regular rhythm",
  LESS_THAN_3_SECONDS: "Less Than 3 Seconds",
  THREE_SECONDS: "Three Seconds",
  MORE_THAN_THREE_SECONDS: "More Than Three Seconds",
  LEG_LEFT_PROXIMAL_THIGH: "Leg Left Proximal Thigh",
  LEG_LEFT_MIDDLE_THIGH: "Leg Left Middle Thigh",
  LEG_LEFT_DISTAL_THIGH: "Leg Left Distal Thigh",
  LEG_LEFT_MIDDLE_LEG: "Leg Left Middle Leg",
  LEG_LEFT_DISTAL_LEG: "Leg Left Distal Leg",
  LEG_RIGHT_PROXIMAL_THIGH: "Leg Right Proximal Thigh",
  LEG_RIGHT_MIDDLE_THIGH: "Leg Right Middle Thigh",
  LEG_RIGHT_DISTAL_THIGH: "Leg Right Distal Thigh",
  LEG_RIGHT_PROXIMAL_LEG: "Leg Right Proximal Leg",
  LEG_RIGHT_MIDDLE_LEG: "Leg Right Middle Leg",
  LEG_RIGHT_DISTAL_LEG: "Leg Right Distal Leg",
  LEG_LEFT_PROXIMAL_LEG: "Leg Left Proximal Leg",
  DRY: "Dry",
  MUCOUS_ABNORMAL: "Mucous Abnormal",
  ENDOTRACHEAL_TUBE: "Endotracheal Tube",
  CANNULATION_SITE: "Cannulation Site",
  DIAGRAM_CANNULATION_SITE: "Diagram Cannulation Site",
  ANTECUBITAL_FOSSA: "Antecubital Fossa",
  HAND: "Hand",
  WRIST: "Wrist",
  FOREARM: "Forearm",
  FOOT: "Foot",
  EXTERNAL_JUGULAR: "External Jugular",
  G14: "G14",
  G16: "G16",
  G18: "G18",
  G22: "G22",
  G20: "G20",
  CENTRAL_LINE: "Central Line",
  FEMORAL: "Femoral",
  SUBCLAVIAN: "Subclavian",
  INTERNAL_JUGULAR: "Internal Jugular",
  CARDIAC_ARREST: "Cardiac Arrest",
  SITE: "Site",
  RESUSCITATION: "Resuscitation",
  SSW: "Ssw",
  PRIORITY: "Priority",
  PEA: "Pea",
  VF: "Vf",
  VT: "Vt",
  ASYS: "Asys",
  IV_ACCESS: "Iv Access",
  INTUBATION: "Intubation",
  POCUS: "Pocus",
  ABG: "Abg",
  REVERSIBLE_CAUSES: "Reversible Causes",
  HYPOXIA: "Hypoxia",
  HYPOVOLEMIA: "Hypovolemia",
  HYPERKALAEMIA: "Hyperkalaemia",
  HYPOKALAEMIA: "Hypokalaemia",
  TENSION_PNEUMOTHORAX: "Tension Pneumothorax",
  TAMPONADE_CARDIAC: "Tamponade Cardiac",
  TOXINS: "Toxins",
  THROMBOSIS_PULMONARY: "Thrombosis Pulmonary",
  THROMBOSIS_CORONARY: "Thrombosis Coronary",
  HYDROGEN_ION_ACIDOSIS: "Hydrogen Ion Acidosis",
  ROSC: "Rosc",
  TEAM_DECISION_TO_STOP: "Team Decision To Stop",
  DNA_CPR_DOCUMENT_FOUND: "Dna Cpr Document Found",
  REASON_CPR_STOPPED: "Reason Cpr Stopped",
  DISPOSITION_AFTER_CPR: "Disposition After Cpr",
  RESUSCITATION_ROOM: "Resuscitation Room",
  ICU: "Icu",
  HDU_SPECIFY: "Hdu Specify",
  GENERAL_WARD_SPECIFY: "General Ward Specify",
  SPO2: "Spo2",
  TEAM_LEADER: "Team Leader",
  TEAM_MEMBERS: "Team Members",
  TIME: "Time",
  DATE: "Date",
  DATE_OF_CPR: "Date Of Cpr",
  ABNORMALITY_DESCRIPTION: "Abnormality Description",
  DESCRIPTION_OF_INJURY: "Description Of Injury",
  PALPATION: "Palpation",
  LIGHT_PALPATION: "Light Palpation",
  DEEP_PALPATION: "Deep Palpation",
  SIDE: "Side",
  HEMORRHOID: "Hemorrhoid",
  FISSURE: "Fissure",
  PROSTATE_DESCRIPTION: "Prostate Description",
  OTHER_RECTAL_GENERAL: "Other Rectal General",
  SPHINCTER_OTHER: "Sphincter Other",
  LACERATION_NOTES: "Laceration Notes",
  HEMATOMAS_NOTES: "Hematomas Notes",
  BLEEDING_NOTES: "Bleeding Notes",
  INFLAMMATION_NOTES: "Inflammation Notes",
  LENGTH: "Length",
  ORAL: "Oral",
  INTRAMUSCULAR: "Intramuscular",
  SUBCUTANEOUS: "Subcutaneous",
  INFILTRATION: "Infiltration",
  INTRATHECAL: "Intrathecal",
  DERMAL: "Dermal",
  INHALED: "Inhaled",
  HEMORRHAGE_CONTROL: "Hemorrhage Control",
  BLOOD_SAMPLE: "Blood Sample",
  CATHETER: "Catheter",
  TRANSFUSION: "Transfusion",
  NG_INSERTION: "Ng Insertion",
  KEEP_WARM: "Keep Warm",
  CAUSE: "Cause",
  CPR_TIME_STOPPED: "Cpr Time Stopped",
  AUSCULTATION_LUNG: "Auscultation Lung",
  MEDICATION: "Medication",
  RHYTHM: "Rhythm",
  SHOCK_ENERGY: "Shock Energy",
  OCCURRENCES: "Occurrences",
  INTERVENTION: "Intervention",
  JAW_THRUST_MANOEUVRE: "Jaw Thrust Manoeuvre",
  SURGICAL_EMPHAYEMA: "Surgical Emphayema",
  LEG_LEFT_PROXIMA_LEG: "Leg Left Proxima Leg",
  MRDT: "Malaria Rapid Diagnostic Test (MRDT)",
  POSITIVE: "Positive",
  HB: "HB",
  NEGATIVE: "Negative",
  INDETERMINATE: "Indeterminate",
  PH: "Ph",
  PCO2: "Pco2",
  PO2: "Po2",
  BASE_EXCESS: "Base Excess",
  LACTATE: "Lactate",
  HCO3: "Hco3",
  ANION_GAPC: "Anion Gapc",
  MOSMC: "Mosmc",
  SO2E: "So2e",
  FO2HBE: "Fo2hbe",
  FHHBE: "Fhhbe",
  CK: "Ck",
  CNA: "Cna",
  CA2: "Ca2",
  CCL: "Ccl",
  P50E: "P50e",
  PREGNANCY_TEST: "Pregnancy Test",
  HIV: "Hiv",
  VDRL: "Vdrl",
  UROBILINOGEN: "Urobilinogen",
  BILIRUBIN: "Bilirubin",
  SPECIFIC_GRAVITY: "Specific Gravity",
  PROTEIN: "Protein",
  NITRITE: "Nitrite",
  KETONES: "Ketones",
  BLOOD: "Blood",
  LEUKOCYTES: "Leukocytes",
  POINT_OF_CARE_ULTRASOUND: "Point Of Care Ultrasound",
  ECG: "Ecg",
  PEFR: "PEFR",
  BLEEDING_FROM_INSIDE_NOSE: "Bleeding From Inside Nose",
  SHIVERING: "Shivering",
  ABDOMINAL_DISTENSION: "Abdominal Distension",
  ABDOMINAL_MASS: "Abdominal Mass",
  ABNORMAL_BIZARRE_BEHAVIOUR: "Abnormal Bizarre Behaviour",
  ABNORMAL_LABORATORY_VALUES: "Abnormal Laboratory Values",
  ALLERGIC_REACTION: "Allergic Reaction",
  AMPUTATION: "Amputation",
  ANIMAL_BITE_DOG: "Animal Bite Dog",
  ANIMAL_BITE_HUMAN: "Animal Bite Human",
  ANIMAL_BITE_HYENA: "Animal Bite Hyena",
  ANIMAL_BITE_CAT: "Animal Bite Cat",
  ANXIETY: "Anxiety",
  APHASIA: "Aphasia",
  BLEEDING_PROBLEM: "Bleeding Problem",
  BLOOD_AND_BODY_FLUID_EXPOSURE: "Blood And Body Fluid Exposure",
  BLOOD_IN_STOOL: "Blood In Stool",
  BURN_INJURY: "Burn Injury",
  CARBON_MONOXIDE_POISONING: "Carbon Monoxide Poisoning",
  CATHETER_CHANGE: "Catheter Change",
  COLD_EXPOSURE: "Cold Exposure",
  CONSTIPATION: "Constipation",
  CONVULSION_SEIZURE: "Convulsion Seizure",
  COOL_PULSELESS_LIMB: "Cool Pulseless Limb",
  COUGH: "Cough",
  DEHYDRATION: "Dehydration",
  DENTAL: "Dental",
  DIARRHOEA: "Diarrhoea",
  DIPLOPIA: "Diplopia",
  DIZZINESS: "Dizziness",
  DRESSING_CHANGE: "Dressing Change",
  DROWNING: "Drowning",
  DRUG_ADMINISTRATION: "Drug Administration",
  DYSPHAGIA: "Dysphagia",
  DYSURIA: "Dysuria",
  EAR_DISCHARGE: "Ear Discharge",
  EARACHE: "Earache",
  ELECTRIC_SHOCK: "Electric Shock",
  EPISTAXIS: "Epistaxis",
  EXPOSURE_TO_COMMUNICABLE_DISEASES: "Exposure To Communicable Diseases",
  EXPOSURE_TO_GAS: "Exposure To Gas",
  EYE_DISCHARGE: "Eye Discharge",
  FAINTING_SYNCOPE_COLLAPSE: "Fainting Syncope Collapse",
  FEVER: "Fever",
  FOCAL_NUMBNESS: "Focal Numbness",
  FOCAL_WEAKNESS: "Focal Weakness",
  FOR_SICK_LEAVE: "For Sick Leave",
  FOREIGN_BODY_EAR: "Foreign Body Ear",
  FOREIGN_BODY_EYE: "Foreign Body Eye",
  FOREIGN_BODY_NOSE: "Foreign Body Nose",
  FOREIGN_BODY_OESOPHAGEAL_OR_ORAL: "Foreign Body Oesophageal Or Oral",
  FOREIGN_BODY_RECTUM: "Foreign Body Rectum",
  FOREIGN_BODY_RESPIRATORY: "Foreign Body Respiratory",
  FOREIGN_BODY_THROAT: "Foreign Body Throat",
  FOREIGN_BODY_VAGINA: "Foreign Body Vagina",
  GENERAL_BODY_WEAKNESS: "General Body Weakness",
  GENITAL_DISCHARGE: "Genital Discharge",
  GENITAL_LESION: "Genital Lesion",
  HAEMATURIA: "Haematuria",
  HAEMOPTYSIS: "Haemoptysis",
  HAEMORRHOID: "Haemorrhoid",
  HEART_PALPITATIONS: "Heart Palpitations",
  HEAVY_MENSTRUATION: "Heavy Menstruation",
  HICCUPS: "Hiccups",
  HIGH_BLOOD_GLUCOSE: "High Blood Glucose",
  HIGH_BLOOD_PRESSURE: "High Blood Pressure",
  HYPERGLYCAEMIA: "Hyperglycaemia",
  HYPERTENSION: "Hypertension",
  HYPERVENTILATION: "Hyperventilation",
  HYPOGLYCAEMIA: "Hypoglycaemia",
  HYPOTHERMIA: "Hypothermia",
  IMAGING_TESTS: "Imaging Tests",
  INJURY_ABDOMEN_BLUNT: "Injury Abdomen Blunt",
  INJURY_ABDOMEN_PENETRATING: "Injury Abdomen Penetrating",
  INJURY_ANAL_OR_RECTAL: "Injury Anal Or Rectal",
  INJURY_CHEMICAL_EXPOSURE: "Injury Chemical Exposure",
  INJURY_CHEST_BLUNT: "Injury Chest Blunt",
  INJURY_CHEST_PENETRATING: "Injury Chest Penetrating",
  INJURY_EAR: "Injury Ear",
  INJURY_ELECTRICAL: "Injury Electrical",
  INJURY_EYE: "Injury Eye",
  INJURY_FACE: "Injury Face",
  INJURY_GENITAL: "Injury Genital",
  INJURY_HEAD: "Injury Head",
  INJURY_LOWER_EXTREMITY: "Injury Lower Extremity",
  INJURY_MAJOR_TRAUMA_BLUNT: "Injury Major Trauma Blunt",
  INJURY_MAJOR_TRAUMA_PENETRATING: "Injury Major Trauma Penetrating",
  INJURY_NECK: "Injury Neck",
  INJURY_NOSE: "Injury Nose",
  INJURY_SPINE: "Injury Spine",
  INJURY_UPPER_EXTREMITY: "Injury Upper Extremity",
  INSOMNIA: "Insomnia",
  INTOXICATION: "Intoxication",
  LOSS_OF_APPETITE: "Loss Of Appetite",
  LOSS_OF_CONSCIOUSNESS: "Loss Of Consciousness",
  LOSS_OF_HEARING: "Loss Of Hearing",
  LUMP_MASS: "Lump Mass",
  MEDICAL_DEVICE_PROBLEM: "Medical Device Problem",
  MUSCLE_CRAMPS: "Muscle Cramps",
  NASAL_CONGESTION: "Nasal Congestion",
  NAUSEA: "Nausea",
  NOSE_BLEED: "Nose Bleed",
  NUMBNESS_PARASTHESIAS: "Numbness Parasthesias",
  ODYNOPHAGIA: "Odynophagia",
  OEDEMA_BILATERAL_LEG: "Oedema Bilateral Leg",
  OEDEMA_GENERALISED: "Oedema Generalised",
  OLIGURIA: "Oliguria",
  PAIN_ABDOMINAL: "Pain Abdominal",
  PAIN_BACK: "Pain Back",
  PAIN_CHEST: "Pain Chest",
  PAIN_FLANK: "Pain Flank",
  PAIN_GROIN: "Pain Groin",
  PAIN_LOWER_EXTREMITY: "Pain Lower Extremity",
  PAIN_NECK: "Pain Neck",
  PAIN_ON_THE_FACE: "Pain On The Face",
  PAIN_RECTAL_OR_PERIANAL: "Pain Rectal Or Perianal",
  PAIN_SCROTAL: "Pain Scrotal",
  PAIN_UPPER_EXTREMITY: "Pain Upper Extremity",
  PAINFUL_EAR: "Painful Ear",
  PAINFUL_EYE: "Painful Eye",
  PAINFUL_URINATION: "Painful Urination",
  PATIENT_SAFETY_CONCERN: "Patient Safety Concern",
  PER_VAGINAL_BLEEDING: "Per Vaginal Bleeding",
  PER_VAGINAL_BLEEDING_WITH_AMENORRHOEA:
    "Per Vaginal Bleeding With Amenorrhoea",
  PHOTOPHOBIA: "Photophobia",
  POISONING: "Poisoning",
  POLYURIA: "Polyuria",
  POSTOPERATIVE_COMPLICATION: "Postoperative Complication",
  PROLONGED_MENSTRUATION: "Prolonged Menstruation",
  PRURITUS: "Pruritus",
  RED_EYE: "Red Eye",
  RING_REMOVAL: "Ring Removal",
  SCROTAL_SWELLING: "Scrotal Swelling",
  SHORTNESS_OF_BREATH: "Shortness Of Breath",
  SKIN_INFECTION: "Skin Infection",
  SKIN_LESION: "Skin Lesion",
  SWOLLEN_JOINT: "Swollen Joint",
  SWOLLEN_LIMB: "Swollen Limb",
  TACHYPNEA: "Tachypnea",
  TEETH_PROBLEM: "Teeth Problem",
  TESTICULAR_PAIN: "Testicular Pain",
  THROAT_PAIN: "Throat Pain",
  URINARY_RETENTION: "Urinary Retention",
  VAGINAL_DISCHARGE: "Vaginal Discharge",
  VERTIGO: "Vertigo",
  VISUAL_PROBLEM: "Visual Problem",
  VOMITING: "Vomiting",
  WOUND_CARE: "Wound Care",
  WOUND_INFECTION: "Wound Infection",
  WOUND_LACERATION: "Wound Laceration",
  SELF_HARM: "Self Harm",
  SEXUAL_ASSAULT: "Sexual Assault",
  SLEEP_DISTURBANCE: "Sleep Disturbance",
  SOCIAL_PROBLEM: "Social Problem",
  SORE_THROAT: "Sore Throat",
  STING_BEE: "Sting Bee",
  STING_SCORPION: "Sting Scorpion",
  STING_WASP: "Sting Wasp",
  SUBSTANCE_WITHDRAWAL_ALCOHOL: "Substance Withdrawal Alcohol",
  SUBSTANCE_WITHDRAWAL_OPIOID: "Substance Withdrawal Opioid",
  SUBSTANCE_WITHDRAWAL_BENZODIAZEPINE: "Substance Withdrawal Benzodiazepine",
  SURGICAL_ADMISSION_FOR_ELECTIVE_SURGERY:
    "Surgical Admission For Elective Surgery",
  SUSPECTED_BOWEL_OBSTRUCTION: "Suspected Bowel Obstruction",
  SUTURE_REMOVAL: "Suture Removal",
  SWELLING_GROIN: "Swelling Groin",
  SWELLING_JOINT: "Swelling Joint",
  SWELLING_NECK: "Swelling Neck",
  SWELLING_PENILE: "Swelling Penile",
  SWELLING_PERI_ORBITAL: "Swelling Peri Orbital",
  SWELLING_SCROTAL: "Swelling Scrotal",
  TINNITUS: "Tinnitus",
  TREMOR: "Tremor",
  UNABLE_TO_SEE: "Unable To See",
  VOMITING_BLOOD: "Vomiting Blood",
  WALKING_DIFFICULTY: "Walking Difficulty",
  WHEEZING: "Wheezing",
  WOUND_REVIEW: "Wound Review",
  PAIN_SHOULDER: "Pain Shoulder",
  PAIN_LOWER_ABDOMEN: "Pain Lower Abdomen",
  WOUND_DISCHARGE: "Wound Discharge",
  NOT_PASSING_STOOLS: "Not Passing Stools",
  FOOD_POISONING: "Food Poisoning",
  VIOLENT_BEHAVIOUR: "Violent Behaviour",
  VISUAL_DISTURBANCE: "Visual Disturbance",
  ASPIRIN_ALLERGY: "Aspirin Allergy",
  IBUPROFEN_ALLERGY: "Ibuprofen Allergy",
  INDOMETHACIN_ALLERGY: "Indomethacin Allergy",
  DICLOFENAC_ALLERGY: "Diclofenac Allergy",
  AMOXICILLIN_ALLERGY: "Amoxicillin Allergy",
  PENICILLIN_V_ALLERGY: "Penicillin V Allergy",
  AMOXICILLIN_CLAVULANIC_ACID_ALLERGY: "Amoxicillin Clavulanic Acid Allergy",
  COTRIMOXAZOLE_ALLERGY: "Cotrimoxazole Allergy",
  SULFADOXIME_PYRIMETHAMINE_ALLERGY: "Sulfadoxime Pyrimethamine Allergy",
  SULPHUR_CONTAINING_MEDICATION_ALLERGY:
    "Sulphur Containing Medication Allergy",
  ALLERGEN: "Allergen",
  ALLERGEN_CATEGORY: "Allergen Category",
  OTHER_MEDICATION_ALLERGY: "Other Medication Allergy",
  OTHER_MEDICATION_ALLERGEN: "Other Medication Allergen",
  OTHER_MEDICAL_SUBSTANCE_ALLERGY: "Other Medical Substance Allergy",
  OTHER_MEDICAL_SUBSTANCE_ALLERGEN: "Other Medical Substance Allergen",
  OTHER_SUBSTANCE_ALLERGY: "Other Substance Allergy",
  OTHER_FOOD_ALLERGY: "Other Food Allergy",
  OTHER_SUBSTANCE_ALLERGEN: "Other Substance Allergen",
  OTHER_FOOD_ALLERGEN: "Other Food Allergen",
  FOOD_ALLERGY: "Food Allergy",
  MEDICAL_SUBSTANCE_ALLERGY: "Medical Substance Allergy",
  SUBSTANCE_ALLERGY: "Substance Allergy",
  RADIOCONTRAST_ALLERGY: "Radiocontrast Allergy",
  LATEX_ALLERGY: "Latex Allergy",
  POLLEN_ALLERGY: "Pollen Allergy",
  BEES_ALLERGY: "Bees Allergy",
  WASPS_ALLERGY: "Wasps Allergy",
  SEAFOOD_ALLERGY: "Seafood Allergy",
  OTHER_FISH_ALLERGY: "Other Fish Allergy",
  EGGS_ALLERGY: "Eggs Allergy",
  PEANUT_ALLERGY: "Peanut Allergy",
  MEDICATION_HISTORY: "Medication History",
  ONCE_A_DAY: "Once A Day",
  TWICE_A_DAY: "Twice A Day",
  THREE_TIMES_A_DAY: "Three Times A Day",
  FOUR_TIMES_A_DAY: "Four Times A Day",
  SIX_TIMES_A_DAY: "Six Times A Day",
  ONCE_A_WEEK: "Once A Week",
  ONCE_A_MONTH: "Once A Month",
  MORNING: "Morning",
  EVENING: "Evening",
  MEDICATION_DOSE: "Medication Dose",
  DOSE_IN_MILLIGRAMS: "Dose In Milligrams",
  MEDICATION_DATE_LAST_TAKEN: "Medication Date Last Taken",
  MEDICATION_DATE_OF_LAST_PRESCRIPTION: "Medication Date Of Last Prescription",
  MEDICATION_DURATION: "Medication Duration",
  OINTMENT: "Ointment",
  INHALER: "Inhaler",
  SUPPOSITORY: "Suppository",
  PESSARY: "Pessary",
  SUSPENSION: "Suspension",
  SHAMPOO: "Shampoo",
  EAR_DROPS: "Ear Drops",
  EYE_PASTE: "Eye Paste",
  ICD11_DIAGNOSIS: "Icd11 Diagnosis",
  DIAGNOSIS_DATE: "Diagnosis Date",
  ADDITIONAL_DIAGNOSIS_DETAILS: "Additional Diagnosis Details",
  ON_TREATMENT: "On Treatment",
  EXPLORATORY_LAPAROTOMY: "Exploratory Laparotomy",
  CAESARIAN_SECTION: "Caesarian Section",
  INCISION_AND_DRAINAGE: "Incision And Drainage",
  THORACOTOMY: "Thoracotomy",
  CIRCUMCISION: "Circumcision",
  DEBRIDEMENT: "Debridement",
  HYSTERECTOMY: "Hysterectomy",
  ORIF: "Orif",
  EXTERNAL_FIXATION: "External Fixation",
  THYROIDECTOMY: "Thyroidectomy",
  SKIN_GRAFT: "Skin Graft",
  OTHER_SURGICAL_PROCEDURE: "Other Surgical Procedure",
  DATE_OF_SURGERY: "Date Of Surgery",
  COMPLICATIONS: "Complications",
  DATE_OF_LAST_MENSTRUAL: "Date Of Last Menstrual",
  GESTATION_WEEKS: "Gestation Weeks",
  PREVIOUS_PREGNANCIES: "Previous Pregnancies",
  SECOND_TRIMESTER_MISCARRIAGE: "Second Trimester Miscarriage",
  PREGENANCY_OUTCOME: "Pregenancy Outcome",
  STILL_BIRTH: "Still Birth",
  LIVE_BIRTH: "Live Birth",
  NUMBER_OF_BIRTHS: "Number Of Births",
  JADELLE: "Jadelle",
  IMPLANON: "Implanon",
  LEVOPLANT: "Levoplant",
  DEPO_PROVERA: "Depo Provera",
  INTRAUTERINE_CONTRACEPTIVE_DEVICE: "Intrauterine Contraceptive Device",
  PROGESTIN_ONLY_PILLS: "Progestin Only Pills",
  VASECTOMY: "Vasectomy",
  TUBAL_LIGATION: "Tubal Ligation",
  COMBINED_ORAL_PILLS: "Combined Oral Pills",
  MALE_FEMALE_CONDOMS: "Male Female Condoms",
  LACTATION_AMENORRHEA: "Lactation Amenorrhea",
  NATURAL: "Natural",
  HEALTH_CENTER_HOSPITALS: "Health Center Hospitals",
  ADMISSION_DATE: "Admission Date",
  ADMISSION_DIAGNOSIS: "Admission Diagnosis",
  ADMISSION_SECTION: "Admission Section",
  SURGICAL_INTERVENTIONS: "Surgical Interventions",
  DISCHARGE_INSTRUCTIONS: "Discharge Instructions",
  FOLLOW_UP: "Follow Up",
  GASTROINTESTINAL: "Gastrointestinal",
  YELLOWINGOFEYESORSKIN: "Yellowingofeyesorskin",
  DYSPEPSIA: "Dyspepsia",
  ABDOMINALPAINS: "Abdominalpains",
  DIFFICULTYINSWALLOWING: "Difficultyinswallowing",
  PAINFULSWALLOWING: "Painfulswallowing",
  ABDOMINALDISTENSION: "Abdominaldistension",
  BLOODYSTOOL: "Bloodystool",
  STOOL_INCONTINENCE: "Stool Incontinence",
  ANAL_SWELLING: "Anal Swelling",
  ANAL_DISCHARGE: "Anal Discharge",
  REVIEW_OF_SYSTEMS_CARDIOPULMONARY: "Review Of Systems Cardiopulmonary",
  REVIEW_OF_SYSTEMS_OTHER: "Review Of Systems Other",
  REVIEW_OF_SYSTEMS_NERVOUS: "Review Of Systems Nervous",
  REVIEW_OF_SYSTEMS_GENITOURINARY: "Review Of Systems Genitourinary",
  REVIEW_OF_SYSTEMS_GASTROINTESTINAL: "Review Of Systems Gastrointestinal",
  REVIEW_OF_SYSTEMS_GENERAL: "Review of systems, general",
  REVIEW_OF_SYSTEMS_TRAUMA: "Review of systems, trauma",
  CONVULSIONS: "Convulsions",
  HALLUCINATIONS: "Hallucinations",
  ABNORMAL_BEHAVIOUR: "Abnormal Behaviour",
  ABNORMAL_GAIT: "Abnormal Gait",
  NUMBNESS: "Numbness",
  NECK_PAINS: "Neck Pains",
  NECK_STIFFNESS: "Neck Stiffness",
  BLOODY_URINE: "Bloody Urine",
  ABNORMAL_VAGINAL_DISCHARGE: "Abnormal Vaginal Discharge",
  VAGINAL_BLEEDING: "Vaginal Bleeding",
  GENITAL_ULCER: "Genital Ulcer",
  URINARY_INCONTINENCE: "Urinary Incontinence",
  ERECTILE_DYSFUNCTION: "Erectile Dysfunction",
  INFERTILITY: "Infertility",
  PROLAPSE: "Prolapse",
  OTHER_GENITOURINARY_CONDITION: "Other Genitourinary Condition",
  ITCHING: "Itching",
  JOINT_PAIN: "Joint Pain",
  NIGHT_SWEATS: "Night Sweats",
  WEIGHT_LOSS: "Weight Loss",
  FATIGUE: "Fatigue",
  POOR_VISION: "Poor Vision",
  TOOTHACHE: "Toothache",
  RUNNY_NOSE: "Runny Nose",
  ANATOMIC_LOCATIONS: "Anatomic Locations",
  PATIENT_DRINKS_ALCOHOL: "Patient Drinks Alcohol",
  ASSAULT: "Assault",
  ROAD_TRAFFIC_ACCIDENT: "Road Traffic Accident",
  FALL: "Fall",
  OCCUPATIONAL_INJURY: "Occupational Injury",
  FAMILY_HISTORY_ASTHMA: "Family History Asthma",
  FAMILY_HISTORY_HYPERTENSION: "Family History Hypertension",
  FAMILY_HISTORY_DIABETES_MELLITUS: "Family History Diabetes Mellitus",
  FAMILY_HISTORY_EPILEPSY: "Family History Epilepsy",
  FAMILY_HISTORY_CANCER: "Family History Cancer",
  FAMILY_HISTORY_TUBERCULOSIS: "Family History Tuberculosis",
  FAMILY_HISTORY_OTHER_CONDITION: "Family History Other Condition",
  ASCITES: "Ascites",
  MEDICATION_FORMULATION: "Medication Formulation",
  MEDICATION_DOSE_UNIT: "Medication Dose Unit",
  MEDICATION_FREQUENCY: "Medication Frequency",
  MEDICATION_ROUTE: "Medication Route",
  MEDICATION_DURATION_UNIT: "Medication Duration Unit",
  SELF_MEDICATED: "Self medicated",
  AGE_AT_MENARCHE: "Age At Menarche",
  FIRST_TRIMESTER_MISCARRIAGE: "First Trimester Miscarriage",
  FREQUENT_URINATION: "Frequent Urination",
  DATE_OF_LAST_MEAL: "Date Of Last Meal",
  TIME_OF_LAST_MEAL: "Time of last meal",
  DESCRIPTION_OF_LAST_MEAL: "Description of Last meal",
  PAIN: "Pain",
  EXCESSIVE_THIRST: "Excessive Thirst",
  HEAT_INTOLERANCE: "Heat Intolerance",
  COLD_INTOLERANCE: "Cold Intolerance",
  INTENTIONAL_POISONING: "Intentional Poisoning",
  ULCER_OR_WOUND: "Ulcer Or Wound",
  PATIENT_SMOKES: "Patient Smokes",
  TRAVEL_HISTORY: "Travel History",
  PHYSICAL_ASSAULT: "Physical Assault",
  TIME_OF_INJURY: "Time Of Injury",
  GUNSHOT: "Gunshot",
  MEDICATION_ALLERGY: "Medication Allergy",
  ALLERGY_DETAILS: "Allergy Details",
  ALLERGY: "Allergy",
  CONFUSION: "Confusion",
  HEADACHE: "Headache",
  STRIDOR: "Stridor",
  OTHER_CONDITION: "Other Condition",
  DURATION_ON_MEDICATION_HOURS: "Duration On Medication Hours",
  DURATION_ON_MEDICATION_DAYS: "Duration On Medication Days",
  DURATION_ON_MEDICATION_WEEKS: "Duration On Medication Weeks",
  DURATION_ON_MEDICATION_MONTHS: "Duration On Medication Months",
  DURATION_ON_MEDICATION_YEARS: "Duration On Medication Years",
  TABLET: "Tablet",
  VIAL: "Vial",
  INTRAVENOUS: "Intravenous",
  POWDER: "Powder",
  SOLUTION: "Solution",
  EYE_OINTMENT: "Eye Ointment",
  EYE_DROPS: "Eye Drops",
  CREAM: "Cream",
  DOSE_IN_MICROGRAMS: "Dose In Micrograms",
  DOSE_IN_GRAMS: "Dose In Grams",
  DOSE_IN_IU: "Dose In Iu",
  DOSE_IN_MILLIMETER: "Dose In Millimeter",
  DOSE_IN_MILLIMOLES: "Dose In Millimoles",
  RELATIONSHIP_TO_PATIENT: "Relationship To Patient",
  INDICATION_FOR_SURGERY: "Indication For Surgery",
  DRUG_GIVEN: "Drug Given",
  SURGICAL_PROCEDURE: "Surgical Procedure",
  HEMORROID: "Hemorroid",
  PROSTRATE_DESCRIPTION: "Prostrate Description",
  DIAGNOSIS: "Diagnosis",
  FUNDO_SCOPY_FINDINGS: "Fundoscopy Findings",
  NOTES: "Notes",
  OBJECTIVE_DATA_HEAD: "Objective data head",
  OBJECTIVE_DATA_CHEST: "Objective data chest",
  OBJECTIVE_DATA_ABDOMEN: "Objective data abdomen",
  OBJECTIVE_DATA_EXTREMITIES: "Objective data extremities",
  INVESTIGATIONS_FBC: "Investigations FBC",
  INVESTIGATIONS_PT: "Investigations PT",
  OTHER_NURSING_NOTES: "Other nursing notes",
  PATIENTS_FLUID_MANAGEMENT: "Patients fluid management",
  INTAKE_FLUID_AMOUNT: "Intake fluid amount",
  OUTPUT_FLUID_AMOUNT: "Output fluid amount",
  OUTPUT_FLUID_TYPE: "Output fluid type",
  FLUID_BALANCE: "Fluid balance",
  FLUID_BALANCE_CHART: "Fluid balance chart",
  BUILDING_COLLAPSE: "Building Collapse",
  PRESENTING_COMPLAINTS: "Presenting Complaints",
  SUBJECTIVE: "subjective",
  OBJECTIVE: "objective",
  ASSESSMENT: "Assessment",
  PLAN: "Plan",
  EVALUATION: "Evaluation",
  REPLAN: "Replan",
  IMPLEMENTATION: "Implementation",

  // to be created
  ARV: "on arv",
  DRUG_START_DATE: "Historical drug start date",
  OTHER_MEDICATION: "Other Medication",
  SURGICAL_HISTORY: "surgical history",
  INTOXICATION_DESCRIPTION: "Intoxication description",
  SOCIAL_HISTORY: "social history",
  FAMILY_HISTORY: "family history",
  UNKNOWN: "unknown",
  PUPIL_SYMMETRICAL: "Pupils symmetrical",
  CONJUNCTIVA: "Conjunctiva",
  ORAL_KS: "Oral KS",
  ORLA_THRUSH: "Oral thrush",
  JVP_RAISED: "JVP raised",
  LYMPHADENOPATHY: "Lymphadenopathy",
  SYMMETRICAL_EXPANSION: "symmetrical expansion",
  THRILL_HEAVES: "thrill heaves",
  PINK: "pink",
  PRESENT: "present",
  HERPES_ZOSTER_SCAR: "Herpes zoster scar",
  SUMMARY: "summary",
  OTHER_AETC_SERVICE_AREA: "Other AETC service area",
  PUPIL: "pupil",
  VISUAL_FIELD_ACUITY: "visual field acuity",
  EYE_MOVEMENTS_NYSTAGMUS: "Eye movements/nystagmus",
  EYE_MOVEMENTS_SENSATION: "Eye movements/sensation",
  HEARING: "hearing",
  TONGUE_MOVEMENTS_TASTES: "tongue movement/tastes",
  COUGH_GAG_REFLEX: "cough gag reflex",
  POWER: "power",
  TONE: "tone",
  REFLEXES: "reflexes",
  PLANTARS: "plantars",
  SENSATION: "sensation",
  COORDINATION: "coordination",
  GAIT: "gait",
  GLOBAL_CHEST_WALL_ABNORMALITY: "global chest wall abnormality",
  ADDED_BREATH_SOUNDS: "added breath sounds",
  BREATH_SOUNDS: "breath sounds",
  CPR_RECORD: "cpr record",
  INTERVENTION_LIST: "intervention list",
  CPR: "cpr",
  IS_NORMAL: "is normal",
  DEEP_TENDERNESS: "deep tenderness",
  DEEP_LOCATION: "Deep Location",
  GUARDING: "guarding",
  REBOUNDING: "rebounding",
  //surgical notes template form concepts
  REASON_FOR_TAKING_MEDICATION: "Reason for taking Medication",
  CANCER_TYPE: "Cancer type",
  ALCOHOL_INTAKE: "Alcohol intake",
  RECREATIONAL_DRUG: "Recreational drug",
  LNMP: "LNMP",
  GESTATIONAL_AGE: "Gestational age",
  PARITY: "Parity",
  REVIEW_OF_SYSTEMS__ENDOCRINE: "Review of systems  endocrine",
  REVIEW_OF_SYSTEMS_CARDIAC: "Review of systems cardiac",
  REVIEW_OF_SYSTEMS_MUSCULOSKELETAL: "Review of systems musculoskeletal",
  REVIEW_OF_SYSTEMS_NEUROLOGIC: "Review of systems neurologic",
  REVIEW_OF_SYSTEMS_PSYCHIATRIC: "Review of systems psychiatric",
  GENERAL_CONDITION: "General condition",
  EYES: "Eyes",
  MOUTH: "Mouth",
  NECK: "Neck",
  CHEST_EXAMINATION: "Chest examination",
  ENDOCRINE_EXAMINATION: "Endocrine examination",
  ABDOMINAL_EXAMINATION: "Abdominal examination",
  CRANIAL_ERVES: "Cranial erves",
  GROSS_MOTOR: "Gross motor",
  PULSATIONS: "Pulsations",
  RECTAL_EXAMINATION: "Rectal examination",
  VAGINAL_EXAMINATION: "Vaginal examination",
  CLERK_NAME: "Clerk name",
  DESIGNATION: "Designation",
  SIGNATURE: "Signature",

  SKIN_PREP: "Skin Prep",
  TUBERCULOSIS: "Tuberculosis (TB)",
  CHRONIC_OBSTRUCTIVE_PULMONARY_DISEASE:
    "Chronic Obstructive Pulmonary Disease (COPD)",
  DIABETES_MELLITUS: "Diabetes Mellitus",
  ASTHMA: "Asthma",
  EPILEPSY: "Epilepsy",
  PREVIOUS_STROKE: "Previous stroke",
  BLEEDING_DISORDERS: "Bleeding disorders",
  COMFORTABLE: "Comfortable",
  ILL: "Ill",
  FIT_FOR_AGE: "Fit for age",
  CANDIDA: "Candida",
  KAPOSI_SARCOMA: "Kaposi's Sarcoma (KS)",
  HYDRATION: "Hydration",
  NODES: "Nodes",
  SUBMENTAL: "Submental",
  EPITHROCHLEAR: "Epithrochlear",
  THYROID: "Thyroid",
  NO_MOVEMENT: "No movement",
  ABNORMAL_EXTENSION: "Abnormal extension (decerebrate posture)",
  ABNORMAL_FLEXION: "Abnormal flexion (decorticate posture)",
  FLEXION_WITHDRAWAL_FROM_PAINFUL_STIMULI:
    "Flexion/Withdrawal from painful stimuli",
  MOVES_TO_LOCALIZE_PAIN: "Moves to localize pain",
  OBEYS_COMMANDS: "Obeys commands",
  NO_SOUND: "No sound",
  INCOMPREHENSIBLE_SOUNDS: "Incomprehensible sounds",
  INAPPROPRIATE_WORDS: "Inappropriate words",
  CONFUSED_AND_DISORIENTED: "Confused and disoriented",
  ORIENTED_TO_TIME: "Oriented to time",
  DOES_NOT_OPEN_EYES: "Does not open eyes",
  OPENS_EYES_IN_RESPONSE_TO_PAIN: "Opens eyes in response to pain",
  OPENS_EYES_IN_RESPONSE_TO_VOICE: "Opens eyes in response to voice",
  OPENS_EYES_SPONTANEOUSLY: "Opens eyes spontaneously",
  FEELING_OF_A_MASS: "Feeling of a mass",
  DIFFICULTY_PAIN_ON_PASSING_STOOLS: "Difficulty/Pain on passing stools",
  NOT_PASSING_FLATUS: "Not passing flatus",
  PASSING_BLOODY_STOOLS: "Passing bloody stools",
  PASSING_MELENA: "Passing melena",
  NOT_PASSING_URINE: "Not passing urine",
  DIFFICULTY_PASSING_URINE: "Difficulty passing urine",
  PASSING_DEEP_YELLOW_URINE: "Passing deep yellow urine",
  PASSING_PUS_IN_URINE: "Passing pus in urine",
  BREAST: "Breast",
  CHEST: "Chest",
  ARM: "Arm",
  THIGH: "Thigh",
  LEG: "Leg",
  HEAD: "Head",
  EYE_PAIN: "Eye pain",
  RHINORRHEA: "Rhinorrhea",
  SINUS_PAIN: "Sinus pain",
  ORAL_LESIONS: "Oral lesions",
  HEAT_TOLERANCE: "Heat tolerance",
  ABNORMAL_HAIR_GROWTH: "Abnormal hair growth",
  COLD_TOLERANCE: "Cold tolerance",
  POLYDIPSIA: "Polydipsia",
  BLEEDING_TENDENCIES: "Bleeding tendencies",
  CHEST_PAIN: "Chest pain",
  PALPITATIONS: "Palpitations",
  CLAUDICATION: "Claudication",
  ORTHOPNOEA: "Orthopnoea",
  PAROXYSMAL_NOCTURNAL_DYSPNOEA: "Paroxysmal nocturnal dyspnoea",
  DYSPNOEA_ON_EXERTION: "Dyspnoea on exertion",
  DYSPNOEA_AT_REST: "Dyspnoea at rest",
  MELENA: "Melena",
  HAEMATOCHEZIA: "Haematochezia",
  CHANGE_IN_APPETITE: "Change in appetite",
  CHANGE_IN_BOWEL_HABIT: "Change in bowel habit",
  HEARTBURN: "Heartburn",
  URGENCY: "Urgency",
  INCONTINENCE: "Incontinence",
  PYURIA: "Pyuria",
  SEXUALLY_TRANSMITTED_INFECTION: "Sexually Transmitted Infection (STI)",
  DYSMENORRHEA: "Dysmenorrhea",
  PELVIC_PAIN: "Pelvic pain",
  CHANGE_IN_SMELL: "Change in smell",
  CHANGE_IN_TASTE: "Change in taste",
  PARAESTHESIAS: "Paraesthesias",
  MUSCLE_WEAKNESS: "Muscle weakness",
  ATAXIA: "Ataxia",
  CHANGE_IN_SPEECH: "Change in speech",
  DEPRESSION: "Depression",
  MANIA: "Mania",
  SUICIDAL_THOUGHTS: "Suicidal thoughts",
  CIGARETTES_PER_DAY: "Cigarettes Per Day",
  SMOKING_HISTORY: "Smoking History",
  QUIT_OVER_A_MONTH_AGO: "Quit over a month ago",
  NEVER_SMOKED: "Never smoked",
  PUPIL_REACTION: "Pupil reaction",
  GENETELIA_EXAMINATION_REQUIRED: "Genetelia examination required",
  SERVICE_AREAS: "Service areas",
  AETC_SERVICE_AREAS: "AETC service areas",
  AUSCULTATION: "Auscultation",
  INTRAOSSEOUS: "Intraosseous",
  REVIEW_OF_SYSTEMS_ENT: "Review of systems ENT",
  CENTRAL_LINE_CANNULATION_SITE: "Central line cannulation site",
  //Gyneacology ward template form concepts
  CHIEF_COMPLAINT: "Chief complaint",
  HISTORY_OF_PRESENT_ILLNESS: "History of present illness",
  GRAVIDITY: "Gravidity",
  NUMBER_OF_LIVING_CHILDREN: "Number of living children",
  MENARCHE: "Menarche",
  MENSTRUAL_CYCLE: "Menstrual cycle",
  DURATION: "Duration", //Not found
  PREV_ABORTION: "Prev Abortion",
  PREV_ECTOPIC: "Prev Ectopic",
  CONSISTENCY: "Consistency",
  COLOR: "Color",
  ODOUR: "Odour",
  AMOUNT: "Amount", // not found
  PREVIOUS_CONTRACEPTIVE: "Previous Contraceptive",
  CONTRACEPTIVE_USE: "Contraceptive use", //concept data type : boolean
  SIDE_EFFECTS: "Side effects",
  CANCER_SCREENING: "Cancer Screening",
  DATE_OF_SCREENING: "Date of screening",
  RESULT: "Results", //UPDATED "Result" TO "Results"// NOT FOUND
  HISTORY_OF_STIS: "History of STIs",
  MENTAL_ILLNESS: "Mental Illness",
  BLOOD_TRANSFUSION: "Blood Transfusion",
  DRUG_ALLERGIES: "Drug Allergies",
  STABLE: "Stable",
  SICK: "Sick", // not found
  CRITICAL: "Critical",
  MILD: "Mild",
  MODERATE: "Moderate",
  SEVERE: "Severe",
  STATS: "Stats",
  RBS: "Random Blood Glucose (RBS)", //UPDATED RBS TO "Random Blood Glucose (RBS)"
  WEIGHT: "Weight", //not Found // Use Normal Weight data type: Numeric
  HEIGHT: "Height", // not found/ Height (cm)  data type: Numeric
  ABDOMEN: "Abdomen",
  VAGINAL_INSPECTION: "Vaginal Inspection",
  EXTREMITIES: "Extremities",
  IMPRESSION: "Impression",
  IMMEDIATE_INTERVENTION: "Immediate Intervention",
  EDD: "EDD", // not found
  CURRENTLY_ON_CONTRACEPTIVE: "Currently on Contraceptive",
  DIGITAL_RECTAL_EXAMINATION_REQUIRED: "Digital Rectal Examination Required", // not found
  GENERAL_EXAMINATION_PLAN: "Treatment plan other remarks",

  GYNAE_BENCH: "Gynae Bench",
  SURGICAL_BENCH: "Surgical bench",
  LEFT_PUPIL_SIZE: "Left pupil size",
  RIGHT_PUPIL_SIZE: "Right pupil size",
  LEFT_PUPIL_REACTION: "Left pupil reaction",
  RIGHT_PUPIL_REACTION: "Right pupil reaction",
  DISCOLORATION: "Discoloration",
  DILATED_VEINS: "Dilated veins",
  HERNIA: "Hernia",
  STOMA: "Stoma",
  VISIBLE_PULSATION: "Visible pulsation",
  ROUNDED: "Rounded",
  PROTUBERANT: "Protuberant",
  SCAPHOID: "Scaphoid",
  OUTCOME: "Outcome",
};

export const conceptNames = {
  DRUG_GIVEN: "Given drugs",
  PRESCRIBED_DOSE: "Prescribed dose",
  MEDICATION_DOSE_UNIT: "Medication Dose Unit",
  MEDICATION_FREQUENCY: "Medication Frequency",
  MEDICATION_DURATION: "Medication Duration",
  MEDICATION_DURATION_UNIT: "Medication Duration Unit",
  MEDICATION_FORMULATION: "Medication Formulation",
  DESCRIPTION: "Description",
  MEDICATION_ROUTE: "Medication Route",
};

export const triageResult = {
  RED: "red",
  GREEN: "green",
  YELLOW: "yellow",
};

export const districts = [
  {
    district_name: "Mchinji",
    district_code: "MC",
    zone_id: 2,
    id: 1,
  },
  {
    district_name: "Dowa",
    district_code: "DA",
    zone_id: 1,
    id: 2,
  },
  {
    district_name: "Dedza",
    district_code: "DE",
    zone_id: 2,
    id: 3,
  },
  {
    district_name: "Lilongwe",
    district_code: "LL",
    zone_id: 2,
    id: 4,
  },
  {
    district_name: "Nkhata Bay",
    district_code: "KB",
    zone_id: 3,
    id: 5,
  },
  {
    district_name: "Chitipa",
    district_code: "CP",
    zone_id: 3,
    id: 6,
  },
  {
    district_name: "Kasungu",
    district_code: "KU",
    zone_id: 1,
    id: 7,
  },
  {
    district_name: "Ntchisi",
    district_code: "NT",
    zone_id: 1,
    id: 8,
  },
  {
    district_name: "Salima",
    district_code: "SA",
    zone_id: 1,
    id: 9,
  },
  {
    district_name: "Nkhotakota",
    district_code: "NK",
    zone_id: 1,
    id: 10,
  },

  {
    district_name: "Ntcheu",
    district_code: "NT",
    zone_id: 2,
    id: 12,
  },

  {
    district_name: "Rumphi",
    district_code: "RU",
    zone_id: 3,
    id: 14,
  },
  {
    district_name: "Karonga",
    district_code: "KA",
    zone_id: 3,
    id: 15,
  },
  {
    district_name: "Mzimba",
    district_code: "MZ",
    zone_id: 3,
    id: 16,
  },
  {
    district_name: "Balaka",
    district_code: "BK",
    zone_id: 4,
    id: 17,
  },
  {
    district_name: "Likoma",
    district_code: "LK",
    zone_id: 3,
    id: 18,
  },
  {
    district_name: "Machinga",
    district_code: "MC",
    zone_id: 4,
    id: 19,
  },
  {
    district_name: "Mangochi",
    district_code: "MG",
    zone_id: 4,
    id: 20,
  },
  {
    district_name: "Mulanje",
    district_code: "MU",
    zone_id: 4,
    id: 21,
  },
  {
    district_name: "Phalombe",
    district_code: "PH",
    zone_id: 4,
    id: 22,
  },
  {
    district_name: "Zomba",
    district_code: "ZA",
    zone_id: 4,
    id: 23,
  },
  {
    district_name: "Blantyre Urban",
    district_code: "BT",
    zone_id: 5,
    id: 24,
  },
  {
    district_name: "Blantyre Rural",
    district_code: "BTR",
    zone_id: 5,
    id: 247,
  },
  {
    district_name: "Chiradzulu",
    district_code: "CR",
    zone_id: 5,
    id: 26,
  },
  {
    district_name: "Chikwawa",
    district_code: "CK",
    zone_id: 5,
    id: 27,
  },
  {
    district_name: "Mwanza",
    district_code: "MW",
    zone_id: 5,
    id: 28,
  },
  {
    district_name: "Neno",
    district_code: "NE",
    zone_id: 5,
    id: 29,
  },
  {
    district_name: "Nsanje",
    district_code: "NS",
    zone_id: 5,
    id: 30,
  },
  {
    district_name: "Thyolo",
    district_code: "TH",
    zone_id: 5,
    id: 31,
  },
];

export const traditionalAuthorities = [
  { id: "Bvumbwe", label: "Bvumbwe" },
  { id: "Chamba", label: "Chamba" },
  { id: "Changata", label: "Changata" },
  { id: "Chikowi", label: "Chikowi" },
  { id: "Chindi", label: "Chindi" },
  { id: "Chiseka", label: "Chiseka" },
  { id: "Chitukula", label: "Chitukula" },
  { id: "Chowe", label: "Chowe" },
  { id: "Dzoole", label: "Dzoole" },
  { id: "Fukamapiri", label: "Fukamapiri" },
  { id: "Ganya", label: "Ganya" },
  { id: "Gomani", label: "Gomani" },
  { id: "Jalasi", label: "Jalasi" },
  { id: "Kabudula", label: "Kabudula" },
  { id: "Kadewere", label: "Kadewere" },
  { id: "Kalolo", label: "Kalolo" },
  { id: "Kayembe", label: "Kayembe" },
  { id: "Kuntaja", label: "Kuntaja" },
  { id: "Kyungu", label: "Kyungu" },
  { id: "Liwonde", label: "Liwonde" },
  { id: "Lundu", label: "Lundu" },
  { id: "Mabulabo", label: "Mabulabo" },
  { id: "Malengachanzi", label: "Malengachanzi" },
  { id: "Maseya", label: "Maseya" },
  { id: "Masula", label: "Masula" },
  { id: "Mavwere", label: "Mavwere" },
  { id: "Mbalachanda", label: "Mbalachanda" },
  { id: "Mbelwa", label: "Mbelwa" },
  { id: "Mbenjere", label: "Mbenjere" },
  { id: "Mchilamwera", label: "Mchilamwera" },
  { id: "Mduwa", label: "Mduwa" },
  { id: "Mlonyeni", label: "Mlonyeni" },
  { id: "Mponda", label: "Mponda" },
  { id: "Mtema", label: "Mtema" },
  { id: "Mthiramanja", label: "Mthiramanja" },
  { id: "Mwakhwawa", label: "Mwakhwawa" },
  { id: "Mwahenga", label: "Mwahenga" },
  { id: "Mwamulowe", label: "Mwamulowe" },
  { id: "Mwase", label: "Mwase" },
  { id: "Mwaulambya", label: "Mwaulambya" },
  { id: "Nankumba", label: "Nankumba" },
  { id: "Njema", label: "Njema" },
  { id: "Nkalo", label: "Nkalo" },
  { id: "Nkhulambe", label: "Nkhulambe" },
  { id: "Nkukula", label: "Nkukula" },
  { id: "Nsomba", label: "Nsomba" },
  { id: "Nyachikadza", label: "Nyachikadza" },
  { id: "Nyambi", label: "Nyambi" },
  { id: "Nyaza", label: "Nyaza" },
  { id: "Phambala", label: "Phambala" },
  { id: "Phambala1", label: "Phambala 1" },
  { id: "Phambala2", label: "Phambala 2" },
  { id: "Pemba", label: "Pemba" },
  { id: "Simphasi", label: "Simphasi" },
  { id: "Siyeni", label: "Siyeni" },
  { id: "Sukumaland", label: "Sukumaland" },
  { id: "Tambala", label: "Tambala" },
  { id: "Tengani", label: "Tengani" },
  { id: "Tengani1", label: "Tengani 1" },
  { id: "Wimbe", label: "Wimbe" },
];

export const malawiVillages = [
  { id: "Chigumula", label: "Chigumula" },
  { id: "Chilinde", label: "Chilinde" },
  { id: "Chinsapo", label: "Chinsapo" },
  { id: "Area 23", label: "Area 23" },
  { id: "Namiyango", label: "Namiyango" },
  { id: "Chirimba", label: "Chirimba" },
  { id: "Chigoli", label: "Chigoli" },
];

export const roles = {
  ADMIN: process.env.NEXT_PUBLIC_SUPER_USER_ROLE as string,
  REGISTRATION_CLERK: process.env
    .NEXT_PUBLIC_REGISTRATIONCLERK_USER_ROLE as string,
  CLINICIAN: process.env.NEXT_PUBLIC_CLINICIAN_USER_ROLE as string,
  NURSE: process.env.NEXT_PUBLIC_NURSE_USER_ROLE as string,
  INITIAL_REGISTRATION_CLERK: process.env
    .NEXT_PUBLIC_HOSPITALATTENDANT_USER_ROLE as string,
  DATA_MANAGER: process.env.NEXT_PUBLIC_DATA_MANAGER as string,
  STUDENT_CLINICIAN: process.env
    .NEXT_PUBLIC_STUDENT_CLINICIAN_USER_ROLE as string,
};

// username: registration, clinician, nurse

export const durationOptions = [
  "Hour(s)",
  "Day(s)",
  "Week(s)",
  "Month(s)",
  "Year(s)",
];

export const templateForms = {
  ORTHOPAEDIC_SPECIALTY_REVIEW: "orthopaedic specialty review",
};

export const attributeType = {
  PHONE_NUMBER_ATTRIBUTE_TYPE: "ba35e3da-8d80-11d8-abbb-0024217bb78e",
  NEXT_OF_KIN: "4fb019c3-e326-48f3-8f39-6822a0e9bc9d",
  GUARDIAN_PHONE_NUMBER: "ba35f2d0-8d80-11d8-abbb-0024217bb78e",
};
